CREATE DATABASE FormsPkm;

use FormsPkm;

CREATE TABLE ArchivoPkm (
	idPkm INT AUTO_INCREMENT,
	autor VARCHAR(100) NOT NULL,
	nombre VARCHAR(100) NOT NULL,
	fecha TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	pkm LONGTEXT NOT NULL,
	CONSTRAINT pk_archivo_pkm PRIMARY KEY(idPkm)
);
