// DO NOT EDIT
// Generated by JFlex 1.9.1 http://jflex.de/
// source: /home/rafael-cayax/Compiladores1_2026/PKM_FORMS_compi1/jflex_y_cup/form_lexer.jflex

package com.example.pkm_forms_proyecto1.analizadores;

import com.example.pkm_forms_proyecto1.backend.MensajeError;
import com.example.pkm_forms_proyecto1.enums.TipoEnum;
import java.util.List;
import java_cup.runtime.*;


@SuppressWarnings("fallthrough")
public class FormLexer implements java_cup.runtime.Scanner {

  /** This character denotes the end of file. */
  public static final int YYEOF = -1;

  /** Initial size of the lookahead buffer. */
  private static final int ZZ_BUFFERSIZE = 16384;

  // Lexical states.
  public static final int YYINITIAL = 0;
  public static final int STRING = 2;
  public static final int INSTRUCCION = 4;
  public static final int COMENTARIO = 6;
  public static final int ESTILO = 8;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = {
     0,  0,  1,  1,  2,  2,  3,  3,  4, 4
  };

  /**
   * Top-level table for translating characters to character classes
   */
  private static final int [] ZZ_CMAP_TOP = zzUnpackcmap_top();

  private static final String ZZ_CMAP_TOP_PACKED_0 =
    "\1\0\37\u0100\1\u0200\267\u0100\10\u0300\u1020\u0100";

  private static int [] zzUnpackcmap_top() {
    int [] result = new int[4352];
    int offset = 0;
    offset = zzUnpackcmap_top(ZZ_CMAP_TOP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackcmap_top(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /**
   * Second-level tables for translating characters to character classes
   */
  private static final int [] ZZ_CMAP_BLOCKS = zzUnpackcmap_blocks();

  private static final String ZZ_CMAP_BLOCKS_PACKED_0 =
    "\11\0\1\1\1\2\1\3\1\4\1\5\22\0\1\1"+
    "\1\6\1\7\1\10\1\11\1\12\1\13\1\0\1\14"+
    "\1\15\1\16\1\17\1\20\1\21\1\22\1\23\12\24"+
    "\1\25\1\26\1\27\1\30\1\31\1\32\1\0\6\33"+
    "\24\34\1\35\1\36\1\37\1\40\1\34\1\0\1\41"+
    "\1\42\1\43\1\44\1\45\1\46\1\47\1\34\1\50"+
    "\1\34\1\51\1\52\1\53\1\54\1\55\2\34\1\56"+
    "\1\57\1\60\1\61\2\34\1\62\1\63\1\64\1\65"+
    "\1\66\1\67\1\70\6\0\1\3\u01a2\0\2\3\326\0"+
    "\u0100\3";

  private static int [] zzUnpackcmap_blocks() {
    int [] result = new int[1024];
    int offset = 0;
    offset = zzUnpackcmap_blocks(ZZ_CMAP_BLOCKS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackcmap_blocks(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /**
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\5\0\1\1\2\2\1\1\1\3\1\1\1\4\1\5"+
    "\1\1\1\6\1\7\1\10\1\11\1\12\1\13\1\14"+
    "\1\15\1\16\1\17\1\20\1\21\1\22\1\23\1\24"+
    "\1\25\1\26\1\27\1\30\1\1\1\31\1\32\1\33"+
    "\1\34\1\33\1\35\2\4\1\3\1\36\1\37\1\40"+
    "\1\21\1\0\1\41\1\42\1\43\1\0\1\44\1\45"+
    "\1\46\5\0\1\47\27\0\1\50\2\0\1\51\3\0"+
    "\1\52\7\0\1\53\3\0\1\54\4\0\1\55";

  private static int [] zzUnpackAction() {
    int [] result = new int[109];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /**
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\71\0\162\0\253\0\344\0\u011d\0\u011d\0\u0156"+
    "\0\u018f\0\u011d\0\u01c8\0\u0201\0\u011d\0\u023a\0\u011d\0\u011d"+
    "\0\u011d\0\u011d\0\u011d\0\u011d\0\u0273\0\u02ac\0\u02e5\0\u011d"+
    "\0\u011d\0\u031e\0\u031e\0\u011d\0\u0357\0\u011d\0\u011d\0\u011d"+
    "\0\u011d\0\u0390\0\u011d\0\u011d\0\u011d\0\u011d\0\u03c9\0\u011d"+
    "\0\u011d\0\u0402\0\u043b\0\u031e\0\u031e\0\u011d\0\u011d\0\u0474"+
    "\0\u011d\0\u011d\0\u011d\0\u04ad\0\u011d\0\u011d\0\u011d\0\u04e6"+
    "\0\u051f\0\u0558\0\u0591\0\u05ca\0\u04ad\0\u0603\0\u063c\0\u0675"+
    "\0\u06ae\0\u06e7\0\u0720\0\u0759\0\u0792\0\u07cb\0\u0804\0\u083d"+
    "\0\u0876\0\u08af\0\u08e8\0\u0921\0\u095a\0\u0993\0\u09cc\0\u0a05"+
    "\0\u0a3e\0\u0a77\0\u0ab0\0\u0ae9\0\u011d\0\u0b22\0\u0b5b\0\u011d"+
    "\0\u0b94\0\u0bcd\0\u0c06\0\u011d\0\u0c3f\0\u0c78\0\u0cb1\0\u0cea"+
    "\0\u0d23\0\u0d5c\0\u0d95\0\u011d\0\u0dce\0\u0e07\0\u0e40\0\u011d"+
    "\0\u0e79\0\u0eb2\0\u0eeb\0\u0f24\0\u011d";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[109];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length() - 1;
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /**
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpacktrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\6\2\7\1\0\1\7\1\10\1\11\1\12\1\13"+
    "\1\14\1\15\1\16\1\17\1\20\1\21\1\22\1\23"+
    "\1\24\1\25\1\26\1\27\1\30\1\31\1\32\1\33"+
    "\1\32\1\34\2\35\1\36\1\6\1\37\1\40\24\35"+
    "\1\41\1\42\1\43\1\44\2\45\1\6\3\0\1\45"+
    "\1\46\26\45\1\47\32\45\1\6\1\7\1\50\1\0"+
    "\1\7\1\10\1\11\1\12\1\13\1\14\1\15\1\16"+
    "\1\17\1\20\1\21\1\22\1\23\1\24\1\25\1\26"+
    "\1\27\1\30\1\31\1\32\1\33\1\32\1\34\2\35"+
    "\1\36\1\6\1\37\1\40\24\35\1\41\1\42\1\43"+
    "\1\44\16\51\1\52\52\51\1\6\2\7\1\0\1\7"+
    "\1\10\1\11\1\53\1\13\1\14\1\15\1\16\1\17"+
    "\1\20\1\21\1\22\1\23\1\24\1\25\1\26\1\27"+
    "\1\30\1\31\1\54\1\33\1\55\1\34\2\35\1\36"+
    "\1\6\1\56\1\40\24\35\1\41\1\42\1\43\1\44"+
    "\73\0\1\7\74\0\1\57\106\0\1\60\6\0\1\60"+
    "\35\0\2\14\4\0\63\14\13\0\1\61\77\0\1\62"+
    "\64\0\1\63\52\0\2\64\4\0\16\64\1\27\44\64"+
    "\30\0\1\57\64\0\1\35\6\0\2\35\4\0\24\35"+
    "\72\0\1\65\11\0\1\66\104\0\1\67\107\0\1\70"+
    "\1\71\2\0\1\72\11\0\1\73\34\0\1\74\6\0"+
    "\1\74\61\0\1\75\105\0\1\76\13\0\1\77\70\0"+
    "\1\100\70\0\1\101\60\0\1\102\47\0\1\103\6\0"+
    "\1\103\100\0\1\104\103\0\1\105\64\0\1\106\72\0"+
    "\1\107\76\0\1\110\32\0\1\111\6\0\1\111\106\0"+
    "\1\112\63\0\1\113\101\0\1\114\73\0\1\115\70\0"+
    "\1\116\34\0\1\117\6\0\1\117\104\0\1\120\66\0"+
    "\1\121\101\0\1\122\60\0\1\123\101\0\1\124\35\0"+
    "\1\125\6\0\1\125\113\0\1\126\70\0\1\127\21\0"+
    "\1\130\122\0\1\131\77\0\1\132\75\0\1\133\22\0"+
    "\1\134\134\0\1\135\101\0\1\136\65\0\1\137\57\0"+
    "\1\140\65\0\1\141\77\0\1\142\66\0\1\143\25\0"+
    "\1\144\125\0\1\145\107\0\1\146\50\0\1\147\34\0"+
    "\1\150\136\0\1\151\65\0\1\152\73\0\1\153\71\0"+
    "\1\154\21\0\1\155\61\0";

  private static int [] zzUnpacktrans() {
    int [] result = new int[3933];
    int offset = 0;
    offset = zzUnpacktrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpacktrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** Error code for "Unknown internal scanner error". */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  /** Error code for "could not match input". */
  private static final int ZZ_NO_MATCH = 1;
  /** Error code for "pushback value was too large". */
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /**
   * Error messages for {@link #ZZ_UNKNOWN_ERROR}, {@link #ZZ_NO_MATCH}, and
   * {@link #ZZ_PUSHBACK_2BIG} respectively.
   */
  private static final String ZZ_ERROR_MSG[] = {
    "Unknown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state {@code aState}
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\5\0\2\11\2\1\1\11\2\1\1\11\1\1\6\11"+
    "\3\1\2\11\2\1\1\11\1\1\4\11\1\1\4\11"+
    "\1\1\2\11\4\1\2\11\1\0\3\11\1\0\3\11"+
    "\5\0\1\1\27\0\1\11\2\0\1\11\3\0\1\11"+
    "\7\0\1\11\3\0\1\11\4\0\1\11";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[109];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** Input device. */
  private java.io.Reader zzReader;

  /** Current state of the DFA. */
  private int zzState;

  /** Current lexical state. */
  private int zzLexicalState = YYINITIAL;

  /**
   * This buffer contains the current text to be matched and is the source of the {@link #yytext()}
   * string.
   */
  private char zzBuffer[] = new char[Math.min(ZZ_BUFFERSIZE, zzMaxBufferLen())];

  /** Text position at the last accepting state. */
  private int zzMarkedPos;

  /** Current text position in the buffer. */
  private int zzCurrentPos;

  /** Marks the beginning of the {@link #yytext()} string in the buffer. */
  private int zzStartRead;

  /** Marks the last character in the buffer, that has been read from input. */
  private int zzEndRead;

  /**
   * Whether the scanner is at the end of file.
   * @see #yyatEOF
   */
  private boolean zzAtEOF;

  /**
   * The number of occupied positions in {@link #zzBuffer} beyond {@link #zzEndRead}.
   *
   * <p>When a lead/high surrogate has been read from the input stream into the final
   * {@link #zzBuffer} position, this will have a value of 1; otherwise, it will have a value of 0.
   */
  private int zzFinalHighSurrogate = 0;

  /** Number of newlines encountered up to the start of the matched text. */
  private int yyline;

  /** Number of characters from the last newline up to the start of the matched text. */
  private int yycolumn;

  /** Number of characters up to the start of the matched text. */
  @SuppressWarnings("unused")
  private long yychar;

  /** Whether the scanner is currently at the beginning of a line. */
  @SuppressWarnings("unused")
  private boolean zzAtBOL = true;

  /** Whether the user-EOF-code has already been executed. */
  private boolean zzEOFDone;

  /* user code: */

	private StringBuilder texto = new StringBuilder();
	private int estadoAnterior = YYINITIAL;
	private int linea;
	private int columna;
	private List<MensajeError> errores;
	
	private Symbol symbol(int type){
		return new Symbol(type, yyline+1, yycolumn+1);
	}
    	
	private Symbol symbol(int type, Object object){
		return new Symbol(type, yyline+1, yycolumn+1, object);
	}

	private void iniciarCadena(){
		yybegin(STRING);
    		texto.setLength(0);
    		linea = yyline+1;
    		columna = yycolumn+1;
    	}
    	
    	private Symbol reportarCadena(){
    		return new Symbol(sym.CADENA, linea, columna, texto.toString());
    	}
    	
    	private void reportarErrorLexico(){
    		int estado = yystate();
    		MensajeError error = new MensajeError(TipoEnum.LEXICO);
            	error.setColumna(yycolumn+1);
            	error.setLinea(yyline+1);
    		if (estado == STRING){
    			error.setDescripcion("cadena no cerrada");
    			error.setLexema(texto.toString());
    		} else {
    			error.setDescripcion("simbolo no reconocido");
              		error.setLexema(yytext());
    		}
    		errores.add(error);
    	}
    	
    	private void cambiarAInstruccion(){
    		estadoAnterior = INSTRUCCION;
    		yybegin(INSTRUCCION);
    	}
    	
    	private void regresarEstado(){
    		yybegin(estadoAnterior);
    		estadoAnterior = YYINITIAL;
    	}
    	


  /**
   * Creates a new scanner
   *
   * @param   in  the java.io.Reader to read input from.
   */
  public FormLexer(java.io.Reader in) {
    this.zzReader = in;
  }


  /** Returns the maximum size of the scanner buffer, which limits the size of tokens. */
  private int zzMaxBufferLen() {
    return Integer.MAX_VALUE;
  }

  /**  Whether the scanner buffer can grow to accommodate a larger token. */
  private boolean zzCanGrow() {
    return true;
  }

  /**
   * Translates raw input code points to DFA table row
   */
  private static int zzCMap(int input) {
    int offset = input & 255;
    return offset == input ? ZZ_CMAP_BLOCKS[offset] : ZZ_CMAP_BLOCKS[ZZ_CMAP_TOP[input >> 8] | offset];
  }

  /**
   * Refills the input buffer.
   *
   * @return {@code false} iff there was new input.
   * @exception java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead - zzStartRead);

      /* translate stored positions */
      zzEndRead -= zzStartRead;
      zzCurrentPos -= zzStartRead;
      zzMarkedPos -= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length - zzFinalHighSurrogate && zzCanGrow()) {
      /* if not, and it can grow: blow it up */
      char newBuffer[] = new char[Math.min(zzBuffer.length * 2, zzMaxBufferLen())];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
    }

    /* fill the buffer with new input */
    int requested = zzBuffer.length - zzEndRead;
    int numRead = zzReader.read(zzBuffer, zzEndRead, requested);

    /* not supposed to occur according to specification of java.io.Reader */
    if (numRead == 0) {
      if (requested == 0) {
        throw new java.io.EOFException("Scan buffer limit reached ["+zzBuffer.length+"]");
      }
      else {
        throw new java.io.IOException(
            "Reader returned 0 characters. See JFlex examples/zero-reader for a workaround.");
      }
    }
    if (numRead > 0) {
      zzEndRead += numRead;
      if (Character.isHighSurrogate(zzBuffer[zzEndRead - 1])) {
        if (numRead == requested) { // We requested too few chars to encode a full Unicode character
          --zzEndRead;
          zzFinalHighSurrogate = 1;
        } else {                    // There is room in the buffer for at least one more char
          int c = zzReader.read();  // Expecting to read a paired low surrogate char
          if (c == -1) {
            return true;
          } else {
            zzBuffer[zzEndRead++] = (char)c;
          }
        }
      }
      /* potentially more input available */
      return false;
    }

    /* numRead < 0 ==> end of stream */
    return true;
  }


  /**
   * Closes the input reader.
   *
   * @throws java.io.IOException if the reader could not be closed.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true; // indicate end of file
    zzEndRead = zzStartRead; // invalidate buffer

    if (zzReader != null) {
      zzReader.close();
    }
  }


  /**
   * Resets the scanner to read from a new input stream.
   *
   * <p>Does not close the old reader.
   *
   * <p>All internal variables are reset, the old input stream <b>cannot</b> be reused (internal
   * buffer is discarded and lost). Lexical state is set to {@code ZZ_INITIAL}.
   *
   * <p>Internal scan buffer is resized down to its initial length, if it has grown.
   *
   * @param reader The new input stream.
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzEOFDone = false;
    yyResetPosition();
    zzLexicalState = YYINITIAL;
    int initBufferSize = Math.min(ZZ_BUFFERSIZE, zzMaxBufferLen());
    if (zzBuffer.length > initBufferSize) {
      zzBuffer = new char[initBufferSize];
    }
  }

  /**
   * Resets the input position.
   */
  private final void yyResetPosition() {
      zzAtBOL  = true;
      zzAtEOF  = false;
      zzCurrentPos = 0;
      zzMarkedPos = 0;
      zzStartRead = 0;
      zzEndRead = 0;
      zzFinalHighSurrogate = 0;
      yyline = 0;
      yycolumn = 0;
      yychar = 0L;
  }


  /**
   * Returns whether the scanner has reached the end of the reader it reads from.
   *
   * @return whether the scanner has reached EOF.
   */
  public final boolean yyatEOF() {
    return zzAtEOF;
  }


  /**
   * Returns the current lexical state.
   *
   * @return the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state.
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   *
   * @return the matched text.
   */
  public final String yytext() {
    return new String(zzBuffer, zzStartRead, zzMarkedPos-zzStartRead);
  }


  /**
   * Returns the character at the given position from the matched text.
   *
   * <p>It is equivalent to {@code yytext().charAt(pos)}, but faster.
   *
   * @param position the position of the character to fetch. A value from 0 to {@code yylength()-1}.
   *
   * @return the character at {@code position}.
   */
  public final char yycharat(int position) {
    return zzBuffer[zzStartRead + position];
  }


  /**
   * How many characters were matched.
   *
   * @return the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occurred while scanning.
   *
   * <p>In a well-formed scanner (no or only correct usage of {@code yypushback(int)} and a
   * match-all fallback rule) this method will only be called with things that
   * "Can't Possibly Happen".
   *
   * <p>If this method is called, something is seriously wrong (e.g. a JFlex bug producing a faulty
   * scanner etc.).
   *
   * <p>Usual syntax/scanner level error handling should be done in error fallback rules.
   *
   * @param errorCode the code of the error message to display.
   */
  private static void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    } catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  }


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * <p>They will be read again by then next call of the scanning method.
   *
   * @param number the number of characters to be read again. This number must not be greater than
   *     {@link #yylength()}.
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Contains user EOF-code, which will be executed exactly once,
   * when the end of file is reached
   */
  private void zzDoEOF() throws java.io.IOException {
    if (!zzEOFDone) {
      zzEOFDone = true;
    
  yyclose();    }
  }




  /**
   * Resumes scanning until the next regular expression is matched, the end of input is encountered
   * or an I/O-Error occurs.
   *
   * @return the next token.
   * @exception java.io.IOException if any I/O-Error occurs.
   */
  @Override  public java_cup.runtime.Symbol next_token() throws java.io.IOException
  {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char[] zzBufferL = zzBuffer;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      boolean zzR = false;
      int zzCh;
      int zzCharCount;
      for (zzCurrentPosL = zzStartRead  ;
           zzCurrentPosL < zzMarkedPosL ;
           zzCurrentPosL += zzCharCount ) {
        zzCh = Character.codePointAt(zzBufferL, zzCurrentPosL, zzMarkedPosL);
        zzCharCount = Character.charCount(zzCh);
        switch (zzCh) {
        case '\u000B':  // fall through
        case '\u000C':  // fall through
        case '\u0085':  // fall through
        case '\u2028':  // fall through
        case '\u2029':
          yyline++;
          yycolumn = 0;
          zzR = false;
          break;
        case '\r':
          yyline++;
          yycolumn = 0;
          zzR = true;
          break;
        case '\n':
          if (zzR)
            zzR = false;
          else {
            yyline++;
            yycolumn = 0;
          }
          break;
        default:
          zzR = false;
          yycolumn += zzCharCount;
        }
      }

      if (zzR) {
        // peek one character ahead if it is
        // (if we have counted one line too much)
        boolean zzPeek;
        if (zzMarkedPosL < zzEndReadL)
          zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        else if (zzAtEOF)
          zzPeek = false;
        else {
          boolean eof = zzRefill();
          zzEndReadL = zzEndRead;
          zzMarkedPosL = zzMarkedPos;
          zzBufferL = zzBuffer;
          if (eof)
            zzPeek = false;
          else
            zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        }
        if (zzPeek) yyline--;
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;

      zzState = ZZ_LEXSTATE[zzLexicalState];

      // set up zzAction for empty match case:
      int zzAttributes = zzAttrL[zzState];
      if ( (zzAttributes & 1) == 1 ) {
        zzAction = zzState;
      }


      zzForAction: {
        while (true) {

          if (zzCurrentPosL < zzEndReadL) {
            zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
            zzCurrentPosL += Character.charCount(zzInput);
          }
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
              zzCurrentPosL += Character.charCount(zzInput);
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMap(zzInput) ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
        zzAtEOF = true;
            zzDoEOF();
              {
                return symbol(sym.EOF);
              }
      }
      else {
        switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
          case 1:
            { reportarErrorLexico();
            }
          // fall through
          case 46: break;
          case 2:
            { /* ignorar espacios en blanco */
            }
          // fall through
          case 47: break;
          case 3:
            { iniciarCadena();
            }
          // fall through
          case 48: break;
          case 4:
            { /* ignorar comentarios */
            }
          // fall through
          case 49: break;
          case 5:
            { return symbol(sym.MODULO);
            }
          // fall through
          case 50: break;
          case 6:
            { return symbol(sym.PARENAPER);
            }
          // fall through
          case 51: break;
          case 7:
            { return symbol(sym.PARENCERRA);
            }
          // fall through
          case 52: break;
          case 8:
            { return symbol(sym.MULTI);
            }
          // fall through
          case 53: break;
          case 9:
            { return symbol(sym.SUMA);
            }
          // fall through
          case 54: break;
          case 10:
            { return symbol(sym.COMA);
            }
          // fall through
          case 55: break;
          case 11:
            { return symbol(sym.RESTA);
            }
          // fall through
          case 56: break;
          case 12:
            { return symbol(sym.PUNTO);
            }
          // fall through
          case 57: break;
          case 13:
            { return symbol(sym.DIVIS);
            }
          // fall through
          case 58: break;
          case 14:
            { return symbol(sym.NUMERO, Integer.parseInt(yytext()));
            }
          // fall through
          case 59: break;
          case 15:
            { return symbol(sym.DOS_PUNTOS);
            }
          // fall through
          case 60: break;
          case 16:
            { return symbol(sym.PUNTO_COMA);
            }
          // fall through
          case 61: break;
          case 17:
            { return symbol(sym.OPERACOMP, yytext());
            }
          // fall through
          case 62: break;
          case 18:
            { return symbol(sym.ASIGN);
            }
          // fall through
          case 63: break;
          case 19:
            { return symbol(sym.COMODIN);
            }
          // fall through
          case 64: break;
          case 20:
            { String lexema = yytext();
								  switch(lexema){
									case "BLACK":
										return symbol(sym.TCOLOR, Tcolor.BLACK);
									case "BLUE":
										return symbol(sym.TCOLOR, Tcolor.BLUE);
									case "content":
										return symbol(sym.CONTENT);
									case "correct":
										return symbol(sym.CORRECT);
									case "CURSIVE":
										return symbol(sym.FUENTE, Fuente.CURSIVE);
									case "DO":
										return symbol(sym.DO);
									case "DOUBLE":
										return symbol(sym.GROSOR, Grosor.DOUBLE);
									case "DOTTED":
										return symbol(sym.GROSOR, Grosor.Double);
									case "draw":
										cambiarAInstruccion(); return symbol(sym.DRAW);
									case "DROP_QUESTION":
										return symbol(sym.DROP_QUESTION);
									case "ELSE":
										return symbol(sym.ELSE);
									case "elements":
										return symbol(sym.ELEMENTS);
									case "FOR":
										return symbol(sym.FOR);
									case "GREEN":
										return symbol(sym.TCOLOR, Tcolor.GREEN);
									case "height":
										return symbol(sym.HEIGHT);
									case "HORIZONTAL":
										return symbol(sym.HORIZONTAL);
									case "IF":
										return symbol(sym.IF);
									case "in":
										return symbol(sym.IN);
									case "label":
										return symbol(sym.LABEL);
									case "LINE":
										return symbol(sym.GROSOR, Grosor.LINE);
									case "MONO":
										return symbol(sym.FUENTE, Fuente.MONO);
									case "MULTIPLE_QUESTION":
										return symbol(sym.MULTIPLE_QUESTION);
									case "number":
										cambiarAInstruccion(); return symbol(sym.TIPO, Tipo.NUMBER);
									case "NUMBER":
										 return symbol(sym.NUMBER);
									case "OPEN_QUESTION":
										return symbol(sym.OPEN_QUESTION);
									case "options":
										return symbol(sym.OPTIONS);
									case "orientation":
										return symbol(sym.ORIENTATION);
									case "pointX":
										return symbol(sym.POINTX);
									case "pointY":
										return symbol(sym.POINTY);
									case "PURPLE":
										return symbol(sym.TCOLOR, Tcolor.PURPLE);
									case "RED":
										return symbol(sym.TCOLOR, Tcolor.RED);
									case "SANS_SERIF":
										return symbol(sym.FUENTE, Fuente.SANS_SERIF);
									case "SECTION":
										return symbol(sym.SECTION);
									case "SELECT_QUESTION":
										return symbol(sym.SELECT_QUESTION);
									case "SKY":
										return symbol(sym.TCOLOR, Tcolor.SKY);
									case "special":
										return symbol(sym.TIPO, Tipo.SPECIAL);
									case "string":
										cambiarAInstruccion(); return symbol(sym.TIPO, Tipo.STRING);
									case "styles":
										yybegin(ESTILO); return symbol(sym.STYLES);
									case "TABLE":
										return symbol(sym.TABLE);
									case "TEXT":
										return symbol(sym.TEXT);
									case "VERTICAL":
										return symbol(sym.VERTICAL);
									case "WHITE":
										return symbol(sym.TCOLOR, Tcolor.WHITE);
									case "WHILE":
										return symbol(sym.WHILE);
									case "who_is_that_pokemon":
										return symbol(sym.POKEMON);
									case "width":
										return symbol(sym.WIDTH);
									case "YELLOW":
										return symbol(sym.TCOLOR, Tcolor.YELLOW);
									default:
										return symbol(sym.IDENTI, lexema);
								}
            }
          // fall through
          case 65: break;
          case 21:
            { return symbol(sym.CORCHEAPER);
            }
          // fall through
          case 66: break;
          case 22:
            { return symbol(sym.CORCHECERRA);
            }
          // fall through
          case 67: break;
          case 23:
            { return symbol(sym.POTEN);
            }
          // fall through
          case 68: break;
          case 24:
            { return symbol(sym.LLAVE_APER);
            }
          // fall through
          case 69: break;
          case 25:
            { return symbol(sym.LLAVE_CERRA);
            }
          // fall through
          case 70: break;
          case 26:
            { return symbol(sym.OPERALOGINOT);
            }
          // fall through
          case 71: break;
          case 27:
            { texto.append(yytext());
            }
          // fall through
          case 72: break;
          case 28:
            { return reportarCadena();
            }
          // fall through
          case 73: break;
          case 29:
            { yybegin(YYINITIAL); return symbol(sym.DELIMIT);
            }
          // fall through
          case 74: break;
          case 30:
            { return symbol(sym.MENOR_Q);
            }
          // fall through
          case 75: break;
          case 31:
            { return symbol(sym.MAYOR_Q);
            }
          // fall through
          case 76: break;
          case 32:
            { yybegin(YYINITIAL); return symbol(sym.CORCHECERRA);
            }
          // fall through
          case 77: break;
          case 33:
            { return symbol(sym.OPERALOGIAND);
            }
          // fall through
          case 78: break;
          case 34:
            { return symbol(sym.RANGO);
            }
          // fall through
          case 79: break;
          case 35:
            { yybegin(COMENTARIO);
            }
          // fall through
          case 80: break;
          case 36:
            { return symbol(sym.OPERALOGIOR);
            }
          // fall through
          case 81: break;
          case 37:
            { texto.append("\\\"");
            }
          // fall through
          case 82: break;
          case 38:
            { yybegin(YYINITIAL);
            }
          // fall through
          case 83: break;
          case 39:
            { return symbol(sym.DECIMAL, Double.parseDouble(yytext()));
            }
          // fall through
          case 84: break;
          case 40:
            { return symbol(sym.HEXADECIMAL, yytext());
            }
          // fall through
          case 85: break;
          case 41:
            { return symbol(sym.COLOR);
            }
          // fall through
          case 86: break;
          case 42:
            { return symbol(sym.BORDER);
            }
          // fall through
          case 87: break;
          case 43:
            { return symbol(sym.TEXT_SIZE);
            }
          // fall through
          case 88: break;
          case 44:
            { return symbol(sym.FONT);
            }
          // fall through
          case 89: break;
          case 45:
            { return symbol(sym.BACKGROUND);
            }
          // fall through
          case 90: break;
          default:
            zzScanError(ZZ_NO_MATCH);
        }
      }
    }
  }


}
