
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package com.example.pkm_forms_proyecto1.analizadores;

import java_cup.runtime.*;
import java_cup.runtime.XMLElement;

/** CUP v0.11b 20160615 (GIT 4ac7450) generated parser.
  */
@SuppressWarnings({"rawtypes"})
public class FormParser extends java_cup.runtime.lr_parser {

 public final Class getSymbolContainer() {
    return sym.class;
}

  /** Default constructor. */
  @Deprecated
  public FormParser() {super();}

  /** Constructor which sets the default scanner. */
  @Deprecated
  public FormParser(java_cup.runtime.Scanner s) {super(s);}

  /** Constructor which sets the default scanner. */
  public FormParser(java_cup.runtime.Scanner s, java_cup.runtime.SymbolFactory sf) {super(s,sf);}

  /** Production table. */
  protected static final short _production_table[][] = 
    unpackFromStrings(new String[] {
    "\000\017\000\002\002\004\000\002\002\004\000\002\002" +
    "\004\000\002\002\004\000\002\002\003\000\002\004\003" +
    "\000\002\005\005\000\002\005\007\000\002\005\006\000" +
    "\002\005\004\000\002\007\003\000\002\007\002\000\002" +
    "\010\003\000\002\010\003\000\002\010\003" });

  /** Access to production table. */
  public short[][] production_table() {return _production_table;}

  /** Parse-action table. */
  protected static final short[][] _action_table = 
    unpackFromStrings(new String[] {
    "\000\031\000\010\003\005\004\011\007\004\001\002\000" +
    "\004\005\031\001\002\000\004\006\030\001\002\000\012" +
    "\002\026\003\005\004\011\007\004\001\002\000\012\002" +
    "\ufffc\003\ufffc\004\ufffc\007\ufffc\001\002\000\002\001\002" +
    "\000\004\007\013\001\002\000\012\002\ufffd\003\ufffd\004" +
    "\ufffd\007\ufffd\001\002\000\006\005\014\006\015\001\002" +
    "\000\004\010\020\001\002\000\012\002\ufffb\003\ufffb\004" +
    "\ufffb\007\ufffb\001\002\000\014\002\ufff6\003\ufff6\004\ufff6" +
    "\006\022\007\ufff6\001\002\000\014\002\ufff4\003\ufff4\004" +
    "\ufff4\006\ufff4\007\ufff4\001\002\000\014\002\ufff3\003\ufff3" +
    "\004\ufff3\006\ufff3\007\ufff3\001\002\000\014\002\ufff5\003" +
    "\ufff5\004\ufff5\006\ufff5\007\ufff5\001\002\000\012\002\ufff7" +
    "\003\ufff7\004\ufff7\007\ufff7\001\002\000\012\002\ufffa\003" +
    "\ufffa\004\ufffa\007\ufffa\001\002\000\012\002\ufffe\003\ufffe" +
    "\004\ufffe\007\ufffe\001\002\000\012\002\uffff\003\uffff\004" +
    "\uffff\007\uffff\001\002\000\004\002\001\001\002\000\012" +
    "\002\000\003\000\004\000\007\000\001\002\000\012\002" +
    "\ufff8\003\ufff8\004\ufff8\007\ufff8\001\002\000\004\010\020" +
    "\001\002\000\014\002\ufff6\003\ufff6\004\ufff6\006\022\007" +
    "\ufff6\001\002\000\012\002\ufff9\003\ufff9\004\ufff9\007\ufff9" +
    "\001\002" });

  /** Access to parse-action table. */
  public short[][] action_table() {return _action_table;}

  /** <code>reduce_goto</code> table. */
  protected static final short[][] _reduce_table = 
    unpackFromStrings(new String[] {
    "\000\031\000\012\002\005\003\011\004\007\005\006\001" +
    "\001\000\002\001\001\000\002\001\001\000\010\003\026" +
    "\004\024\005\006\001\001\000\002\001\001\000\004\003" +
    "\023\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\010\003\020\006\016\010\015\001\001\000" +
    "\002\001\001\000\004\007\022\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\010\003" +
    "\020\006\016\010\031\001\001\000\004\007\032\001\001" +
    "\000\002\001\001" });

  /** Access to <code>reduce_goto</code> table. */
  public short[][] reduce_table() {return _reduce_table;}

  /** Instance of action encapsulation class. */
  protected CUP$FormParser$actions action_obj;

  /** Action encapsulation object initializer. */
  protected void init_actions()
    {
      action_obj = new CUP$FormParser$actions(this);
    }

  /** Invoke a user supplied parse action. */
  public java_cup.runtime.Symbol do_action(
    int                        act_num,
    java_cup.runtime.lr_parser parser,
    java.util.Stack            stack,
    int                        top)
    throws java.lang.Exception
  {
    /* call code in generated class */
    return action_obj.CUP$FormParser$do_action(act_num, parser, stack, top);
  }

  /** Indicates start state. */
  public int start_state() {return 0;}
  /** Indicates start production. */
  public int start_production() {return 0;}

  /** <code>EOF</code> Symbol index. */
  public int EOF_sym() {return 0;}

  /** <code>error</code> Symbol index. */
  public int error_sym() {return 1;}


/** Cup generated class to encapsulate user supplied action code.*/
@SuppressWarnings({"rawtypes", "unchecked", "unused"})
class CUP$FormParser$actions {
  private final FormParser parser;

  /** Constructor */
  CUP$FormParser$actions(FormParser parser) {
    this.parser = parser;
  }

  /** Method 0 with the actual generated action code for actions 0 to 300. */
  public final java_cup.runtime.Symbol CUP$FormParser$do_action_part00000000(
    int                        CUP$FormParser$act_num,
    java_cup.runtime.lr_parser CUP$FormParser$parser,
    java.util.Stack            CUP$FormParser$stack,
    int                        CUP$FormParser$top)
    throws java.lang.Exception
    {
      /* Symbol object for return from actions */
      java_cup.runtime.Symbol CUP$FormParser$result;

      /* select the action based on the action number */
      switch (CUP$FormParser$act_num)
        {
          /*. . . . . . . . . . . . . . . . . . . .*/
          case 0: // $START ::= formulario EOF 
            {
              Object RESULT =null;
		int start_valleft = ((java_cup.runtime.Symbol)CUP$FormParser$stack.elementAt(CUP$FormParser$top-1)).left;
		int start_valright = ((java_cup.runtime.Symbol)CUP$FormParser$stack.elementAt(CUP$FormParser$top-1)).right;
		Object start_val = (Object)((java_cup.runtime.Symbol) CUP$FormParser$stack.elementAt(CUP$FormParser$top-1)).value;
		RESULT = start_val;
              CUP$FormParser$result = parser.getSymbolFactory().newSymbol("$START",0, ((java_cup.runtime.Symbol)CUP$FormParser$stack.elementAt(CUP$FormParser$top-1)), ((java_cup.runtime.Symbol)CUP$FormParser$stack.peek()), RESULT);
            }
          /* ACCEPT */
          CUP$FormParser$parser.done_parsing();
          return CUP$FormParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 1: // formulario ::= formulario pregunta 
            {
              Object RESULT =null;

              CUP$FormParser$result = parser.getSymbolFactory().newSymbol("formulario",0, ((java_cup.runtime.Symbol)CUP$FormParser$stack.elementAt(CUP$FormParser$top-1)), ((java_cup.runtime.Symbol)CUP$FormParser$stack.peek()), RESULT);
            }
          return CUP$FormParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 2: // formulario ::= formulario instruccion 
            {
              Object RESULT =null;

              CUP$FormParser$result = parser.getSymbolFactory().newSymbol("formulario",0, ((java_cup.runtime.Symbol)CUP$FormParser$stack.elementAt(CUP$FormParser$top-1)), ((java_cup.runtime.Symbol)CUP$FormParser$stack.peek()), RESULT);
            }
          return CUP$FormParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 3: // formulario ::= instruccion pregunta 
            {
              Object RESULT =null;

              CUP$FormParser$result = parser.getSymbolFactory().newSymbol("formulario",0, ((java_cup.runtime.Symbol)CUP$FormParser$stack.elementAt(CUP$FormParser$top-1)), ((java_cup.runtime.Symbol)CUP$FormParser$stack.peek()), RESULT);
            }
          return CUP$FormParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 4: // formulario ::= pregunta 
            {
              Object RESULT =null;

              CUP$FormParser$result = parser.getSymbolFactory().newSymbol("formulario",0, ((java_cup.runtime.Symbol)CUP$FormParser$stack.peek()), ((java_cup.runtime.Symbol)CUP$FormParser$stack.peek()), RESULT);
            }
          return CUP$FormParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 5: // instruccion ::= variable 
            {
              Object RESULT =null;

              CUP$FormParser$result = parser.getSymbolFactory().newSymbol("instruccion",2, ((java_cup.runtime.Symbol)CUP$FormParser$stack.peek()), ((java_cup.runtime.Symbol)CUP$FormParser$stack.peek()), RESULT);
            }
          return CUP$FormParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 6: // variable ::= TIPO IDENTI DELIMIT 
            {
              Object RESULT =null;

              CUP$FormParser$result = parser.getSymbolFactory().newSymbol("variable",3, ((java_cup.runtime.Symbol)CUP$FormParser$stack.elementAt(CUP$FormParser$top-2)), ((java_cup.runtime.Symbol)CUP$FormParser$stack.peek()), RESULT);
            }
          return CUP$FormParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 7: // variable ::= TIPO IDENTI ASIGN valor delimit 
            {
              Object RESULT =null;

              CUP$FormParser$result = parser.getSymbolFactory().newSymbol("variable",3, ((java_cup.runtime.Symbol)CUP$FormParser$stack.elementAt(CUP$FormParser$top-4)), ((java_cup.runtime.Symbol)CUP$FormParser$stack.peek()), RESULT);
            }
          return CUP$FormParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 8: // variable ::= IDENTI ASIGN valor delimit 
            {
              Object RESULT =null;

              CUP$FormParser$result = parser.getSymbolFactory().newSymbol("variable",3, ((java_cup.runtime.Symbol)CUP$FormParser$stack.elementAt(CUP$FormParser$top-3)), ((java_cup.runtime.Symbol)CUP$FormParser$stack.peek()), RESULT);
            }
          return CUP$FormParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 9: // variable ::= error DELIMIT 
            {
              Object RESULT =null;

              CUP$FormParser$result = parser.getSymbolFactory().newSymbol("variable",3, ((java_cup.runtime.Symbol)CUP$FormParser$stack.elementAt(CUP$FormParser$top-1)), ((java_cup.runtime.Symbol)CUP$FormParser$stack.peek()), RESULT);
            }
          return CUP$FormParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 10: // delimit ::= DELIMIT 
            {
              Object RESULT =null;

              CUP$FormParser$result = parser.getSymbolFactory().newSymbol("delimit",5, ((java_cup.runtime.Symbol)CUP$FormParser$stack.peek()), ((java_cup.runtime.Symbol)CUP$FormParser$stack.peek()), RESULT);
            }
          return CUP$FormParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 11: // delimit ::= 
            {
              Object RESULT =null;

              CUP$FormParser$result = parser.getSymbolFactory().newSymbol("delimit",5, ((java_cup.runtime.Symbol)CUP$FormParser$stack.peek()), RESULT);
            }
          return CUP$FormParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 12: // valor ::= pregunta 
            {
              Object RESULT =null;

              CUP$FormParser$result = parser.getSymbolFactory().newSymbol("valor",6, ((java_cup.runtime.Symbol)CUP$FormParser$stack.peek()), ((java_cup.runtime.Symbol)CUP$FormParser$stack.peek()), RESULT);
            }
          return CUP$FormParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 13: // valor ::= expr 
            {
              Object RESULT =null;

              CUP$FormParser$result = parser.getSymbolFactory().newSymbol("valor",6, ((java_cup.runtime.Symbol)CUP$FormParser$stack.peek()), ((java_cup.runtime.Symbol)CUP$FormParser$stack.peek()), RESULT);
            }
          return CUP$FormParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 14: // valor ::= CADENA 
            {
              Object RESULT =null;

              CUP$FormParser$result = parser.getSymbolFactory().newSymbol("valor",6, ((java_cup.runtime.Symbol)CUP$FormParser$stack.peek()), ((java_cup.runtime.Symbol)CUP$FormParser$stack.peek()), RESULT);
            }
          return CUP$FormParser$result;

          /* . . . . . .*/
          default:
            throw new Exception(
               "Invalid action number "+CUP$FormParser$act_num+"found in internal parse table");

        }
    } /* end of method */

  /** Method splitting the generated action code into several parts. */
  public final java_cup.runtime.Symbol CUP$FormParser$do_action(
    int                        CUP$FormParser$act_num,
    java_cup.runtime.lr_parser CUP$FormParser$parser,
    java.util.Stack            CUP$FormParser$stack,
    int                        CUP$FormParser$top)
    throws java.lang.Exception
    {
              return CUP$FormParser$do_action_part00000000(
                               CUP$FormParser$act_num,
                               CUP$FormParser$parser,
                               CUP$FormParser$stack,
                               CUP$FormParser$top);
    }
}

}
