
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package com.example.pkm_forms_proyecto1.analizadores;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int IDENTI = 5;
  public static final int ASIGN = 3;
  public static final int error = 1;
  public static final int DELIMIT = 4;
  public static final int TIPO = 2;
  public static final int EOF = 0;
  public static final int CADENA = 6;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "TIPO",
  "ASIGN",
  "DELIMIT",
  "IDENTI",
  "CADENA"
  };
}

