
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package com.example.pkm_forms_proyecto1.analizadores;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int OPERALOGIAND = 39;
  public static final int SELECT_QUESTION = 54;
  public static final int HEXADECIMAL = 68;
  public static final int TEXT_SIZE = 59;
  public static final int POKEMON = 71;
  public static final int MENOR_IGUAL = 32;
  public static final int MENOR_QUE = 33;
  public static final int TABLE = 57;
  public static final int DIVIS = 14;
  public static final int DROP_QUESTION = 18;
  public static final int DIFERENTE = 13;
  public static final int ELEMENTS = 19;
  public static final int DRAW = 17;
  public static final int OPEN_QUESTION = 38;
  public static final int LLAVE_APER = 28;
  public static final int TORIENTACION = 64;
  public static final int NUMERO = 65;
  public static final int MAYOR_QUE = 31;
  public static final int LLAVE_CERRA = 29;
  public static final int FONT = 21;
  public static final int BACKGROUND = 3;
  public static final int TEXT = 58;
  public static final int MULTI = 35;
  public static final int FUENTE = 72;
  public static final int DOS_PUNTOS = 16;
  public static final int OPERALOGINOT = 41;
  public static final int WIDTH = 60;
  public static final int PUNTO_COMA = 50;
  public static final int STYLES = 55;
  public static final int NUMBER = 37;
  public static final int COMA = 5;
  public static final int MODULO = 34;
  public static final int DELIMIT = 12;
  public static final int IGUAL = 25;
  public static final int WHILE = 61;
  public static final int TIPO = 63;
  public static final int DECIMAL = 66;
  public static final int DO = 15;
  public static final int FOR = 22;
  public static final int COMODIN = 6;
  public static final int ORIENTATION = 43;
  public static final int ELSE = 20;
  public static final int MULTIPLE_QUESTION = 36;
  public static final int CORCHEAPER = 9;
  public static final int CORRECT = 11;
  public static final int CONTENT = 7;
  public static final int EOF = 0;
  public static final int PUNTO = 49;
  public static final int SUMA = 56;
  public static final int ASIGN = 2;
  public static final int LABEL = 27;
  public static final int POTEN = 48;
  public static final int IN = 26;
  public static final int error = 1;
  public static final int RESTA = 52;
  public static final int IF = 24;
  public static final int COLOR = 8;
  public static final int PARENAPER = 44;
  public static final int PARENCERRA = 45;
  public static final int CORCHECERRA = 10;
  public static final int BORDER = 4;
  public static final int OPERALOGIOR = 40;
  public static final int HEIGHT = 23;
  public static final int RANGO = 51;
  public static final int IDENTI = 69;
  public static final int TCOLOR = 70;
  public static final int CADENA = 67;
  public static final int GROSOR = 62;
  public static final int POINTY = 47;
  public static final int OPTIONS = 42;
  public static final int POINTX = 46;
  public static final int MAYOR_IGUAL = 30;
  public static final int SECTION = 53;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "ASIGN",
  "BACKGROUND",
  "BORDER",
  "COMA",
  "COMODIN",
  "CONTENT",
  "COLOR",
  "CORCHEAPER",
  "CORCHECERRA",
  "CORRECT",
  "DELIMIT",
  "DIFERENTE",
  "DIVIS",
  "DO",
  "DOS_PUNTOS",
  "DRAW",
  "DROP_QUESTION",
  "ELEMENTS",
  "ELSE",
  "FONT",
  "FOR",
  "HEIGHT",
  "IF",
  "IGUAL",
  "IN",
  "LABEL",
  "LLAVE_APER",
  "LLAVE_CERRA",
  "MAYOR_IGUAL",
  "MAYOR_QUE",
  "MENOR_IGUAL",
  "MENOR_QUE",
  "MODULO",
  "MULTI",
  "MULTIPLE_QUESTION",
  "NUMBER",
  "OPEN_QUESTION",
  "OPERALOGIAND",
  "OPERALOGIOR",
  "OPERALOGINOT",
  "OPTIONS",
  "ORIENTATION",
  "PARENAPER",
  "PARENCERRA",
  "POINTX",
  "POINTY",
  "POTEN",
  "PUNTO",
  "PUNTO_COMA",
  "RANGO",
  "RESTA",
  "SECTION",
  "SELECT_QUESTION",
  "STYLES",
  "SUMA",
  "TABLE",
  "TEXT",
  "TEXT_SIZE",
  "WIDTH",
  "WHILE",
  "GROSOR",
  "TIPO",
  "TORIENTACION",
  "NUMERO",
  "DECIMAL",
  "CADENA",
  "HEXADECIMAL",
  "IDENTI",
  "TCOLOR",
  "POKEMON",
  "FUENTE"
  };
}

