
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package com.example.pkm_forms_proyecto1.pkm.analizadores;

import android.util.Log;

import java_cup.runtime.*;

import com.example.pkm_forms_proyecto1.excepciones.PkmException;
import com.example.pkm_forms_proyecto1.pkm.Border;
import com.example.pkm_forms_proyecto1.pkm.ClaseColor;
import com.example.pkm_forms_proyecto1.pkm.Estiloui;
import com.example.pkm_forms_proyecto1.pkm.Nodoui;
import com.example.pkm_forms_proyecto1.pkm.ConversorColores;
import com.example.pkm_forms_proyecto1.enums.TColor;
import com.example.pkm_forms_proyecto1.enums.TLetra;
import com.example.pkm_forms_proyecto1.enums.Orientacion;
import com.example.pkm_forms_proyecto1.enums.TipoBorde;
import com.example.pkm_forms_proyecto1.pkm.Texto;
import com.example.pkm_forms_proyecto1.pkm.contenedor.Seccion;
import com.example.pkm_forms_proyecto1.pkm.contenedor.Tabla;
import com.example.pkm_forms_proyecto1.pkm.preguntas.PreguntaAbierta;
import com.example.pkm_forms_proyecto1.pkm.preguntas.PreguntaDesplegable;
import com.example.pkm_forms_proyecto1.pkm.preguntas.PreguntaMultiple;
import com.example.pkm_forms_proyecto1.pkm.preguntas.PreguntaSeleccion;
import java.util.LinkedList;
import java.util.List;
import java_cup.runtime.XMLElement;

/** CUP v0.11b 20160615 (GIT 4ac7450) generated parser.
  */
@SuppressWarnings({"rawtypes"})
public class PkmParser extends java_cup.runtime.lr_parser {

 public final Class getSymbolContainer() {
    return sym.class;
}

  /** Default constructor. */
  @Deprecated
  public PkmParser() {super();}

  /** Constructor which sets the default scanner. */
  @Deprecated
  public PkmParser(java_cup.runtime.Scanner s) {super(s);}

  /** Constructor which sets the default scanner. */
  public PkmParser(java_cup.runtime.Scanner s, java_cup.runtime.SymbolFactory sf) {super(s,sf);}

  /** Production table. */
  protected static final short _production_table[][] = 
    unpackFromStrings(new String[] {
    "\000\104\000\002\002\004\000\002\004\004\000\002\004" +
    "\004\000\002\004\003\000\002\004\003\000\002\017\003" +
    "\000\002\017\003\000\002\017\003\000\002\017\003\000" +
    "\002\047\005\000\002\050\005\000\002\050\003\000\002" +
    "\050\002\000\002\022\004\000\002\024\016\000\002\034" +
    "\004\000\002\034\010\000\002\023\004\000\002\025\016" +
    "\000\002\035\004\000\002\035\010\000\002\051\005\000" +
    "\002\052\005\000\002\052\003\000\002\021\004\000\002" +
    "\026\016\000\002\036\004\000\002\036\010\000\002\020" +
    "\004\000\002\027\012\000\002\037\004\000\002\037\010" +
    "\000\002\016\004\000\002\030\012\000\002\040\004\000" +
    "\002\040\010\000\002\005\004\000\002\005\003\000\002" +
    "\031\003\000\002\031\003\000\002\031\003\000\002\031" +
    "\003\000\002\013\006\000\002\033\015\000\002\012\012" +
    "\000\002\011\004\000\002\011\003\000\002\007\012\000" +
    "\002\006\004\000\002\006\003\000\002\032\012\000\002" +
    "\002\006\000\002\014\006\000\002\015\017\000\002\010" +
    "\012\000\002\003\006\000\002\042\010\000\002\041\006" +
    "\000\002\044\010\000\002\045\011\000\002\046\011\000" +
    "\002\053\011\000\002\054\021\000\002\054\005\000\002" +
    "\043\003\000\002\043\011\000\002\043\011\000\002\043" +
    "\003" });

  /** Access to production table. */
  public short[][] production_table() {return _production_table;}

  /** Parse-action table. */
  protected static final short[][] _action_table = 
    unpackFromStrings(new String[] {
    "\000\u0111\000\004\004\007\001\002\000\006\002\u0112\004" +
    "\007\001\002\000\006\002\ufffd\004\ufffd\001\002\000\004" +
    "\004\013\001\002\000\006\031\213\035\214\001\002\000" +
    "\006\002\ufffe\004\ufffe\001\002\000\004\004\013\001\002" +
    "\000\004\004\123\001\002\000\004\034\014\001\002\000" +
    "\004\007\015\001\002\000\004\004\017\001\002\000\004" +
    "\004\073\001\002\000\004\011\065\001\002\000\004\004" +
    "\021\001\002\000\006\006\022\013\024\001\002\000\004" +
    "\010\027\001\002\000\004\004\uffc9\001\002\000\004\034" +
    "\025\001\002\000\004\007\026\001\002\000\004\004\uffc2" +
    "\001\002\000\004\044\030\001\002\000\004\010\031\001" +
    "\002\000\004\037\032\001\002\000\004\010\033\001\002" +
    "\000\004\011\034\001\002\000\004\020\035\001\002\000" +
    "\012\004\042\026\040\036\041\043\036\001\002\000\004" +
    "\013\uffbe\001\002\000\004\013\057\001\002\000\004\044" +
    "\051\001\002\000\004\013\uffc1\001\002\000\004\044\043" +
    "\001\002\000\004\010\044\001\002\000\004\044\045\001" +
    "\002\000\004\010\046\001\002\000\004\044\047\001\002" +
    "\000\004\007\050\001\002\000\004\013\uffc0\001\002\000" +
    "\004\010\052\001\002\000\004\044\053\001\002\000\004" +
    "\010\054\001\002\000\004\044\055\001\002\000\004\027" +
    "\056\001\002\000\004\013\uffbf\001\002\000\004\007\060" +
    "\001\002\000\004\004\061\001\002\000\004\013\062\001" +
    "\002\000\004\034\063\001\002\000\004\007\064\001\002" +
    "\000\004\004\uffc3\001\002\000\004\020\066\001\002\000" +
    "\012\004\042\026\040\036\041\043\036\001\002\000\004" +
    "\013\070\001\002\000\004\007\071\001\002\000\004\004" +
    "\uffc7\001\002\000\004\004\103\001\002\000\004\005\074" +
    "\001\002\000\004\011\075\001\002\000\004\020\076\001" +
    "\002\000\012\004\042\026\040\036\041\043\036\001\002" +
    "\000\004\013\100\001\002\000\004\007\101\001\002\000" +
    "\004\004\uffc6\001\002\000\004\004\113\001\002\000\004" +
    "\017\104\001\002\000\004\016\105\001\002\000\004\020" +
    "\106\001\002\000\004\041\107\001\002\000\004\013\110" +
    "\001\002\000\004\007\111\001\002\000\004\004\uffc5\001" +
    "\002\000\004\004\uffc8\001\002\000\004\030\114\001\002" +
    "\000\004\033\115\001\002\000\004\020\116\001\002\000" +
    "\004\044\117\001\002\000\004\013\120\001\002\000\004" +
    "\007\121\001\002\000\004\004\uffc4\001\002\000\004\004" +
    "\374\001\002\000\004\012\124\001\002\000\004\007\125" +
    "\001\002\000\004\004\130\001\002\000\004\004\uffd3\001" +
    "\002\000\004\004\367\001\002\000\004\021\131\001\002" +
    "\000\004\007\132\001\002\000\004\004\134\001\002\000" +
    "\004\004\361\001\002\000\004\015\136\001\002\000\004" +
    "\004\uffd0\001\002\000\004\007\137\001\002\000\004\004" +
    "\145\001\002\000\006\007\352\013\350\001\002\000\004" +
    "\004\uffdb\001\002\000\006\007\341\013\337\001\002\000" +
    "\004\004\333\001\002\000\004\004\uffda\001\002\000\020" +
    "\014\215\024\216\025\217\030\212\031\213\032\220\035" +
    "\214\001\002\000\004\004\uffd8\001\002\000\004\004\ufffb" +
    "\001\002\000\004\004\ufffc\001\002\000\006\007\203\013" +
    "\202\001\002\000\004\004\uffd9\001\002\000\006\007\172" +
    "\013\170\001\002\000\004\004\ufff9\001\002\000\004\004" +
    "\ufffa\001\002\000\006\007\161\013\160\001\002\000\004" +
    "\004\uffe5\001\002\000\004\007\167\001\002\000\004\004" +
    "\013\001\002\000\004\004\163\001\002\000\004\013\164" +
    "\001\002\000\004\025\165\001\002\000\004\007\166\001" +
    "\002\000\004\004\uffe2\001\002\000\004\004\uffe3\001\002" +
    "\000\004\007\200\001\002\000\004\004\uffe9\001\002\000" +
    "\004\004\013\001\002\000\004\004\174\001\002\000\004" +
    "\013\175\001\002\000\004\014\176\001\002\000\004\007" +
    "\177\001\002\000\004\004\uffe6\001\002\000\004\004\uffe7" +
    "\001\002\000\004\004\uffe1\001\002\000\004\007\211\001" +
    "\002\000\004\004\013\001\002\000\004\004\205\001\002" +
    "\000\004\013\206\001\002\000\004\030\207\001\002\000" +
    "\004\007\210\001\002\000\004\004\uffde\001\002\000\004" +
    "\004\uffdf\001\002\000\004\020\325\001\002\000\004\020" +
    "\312\001\002\000\004\020\301\001\002\000\004\020\267" +
    "\001\002\000\004\020\247\001\002\000\004\020\241\001" +
    "\002\000\004\020\221\001\002\000\004\044\222\001\002" +
    "\000\004\010\223\001\002\000\004\044\224\001\002\000" +
    "\004\010\225\001\002\000\004\042\226\001\002\000\004" +
    "\010\227\001\002\000\004\022\231\001\002\000\004\010" +
    "\237\001\002\000\004\042\232\001\002\000\006\010\uffea" +
    "\023\uffea\001\002\000\006\010\234\023\235\001\002\000" +
    "\004\042\236\001\002\000\004\010\uffec\001\002\000\006" +
    "\010\uffeb\023\uffeb\001\002\000\004\044\240\001\002\000" +
    "\006\007\uffef\013\uffef\001\002\000\004\044\242\001\002" +
    "\000\004\010\243\001\002\000\004\044\244\001\002\000" +
    "\004\010\245\001\002\000\004\042\246\001\002\000\006" +
    "\007\uffe4\013\uffe4\001\002\000\004\044\250\001\002\000" +
    "\004\010\251\001\002\000\004\044\252\001\002\000\004" +
    "\010\253\001\002\000\004\042\254\001\002\000\004\010" +
    "\255\001\002\000\004\022\231\001\002\000\004\010\257" +
    "\001\002\000\004\022\260\001\002\000\010\010\ufff5\023" +
    "\ufff5\044\262\001\002\000\006\007\ufff3\013\ufff3\001\002" +
    "\000\006\010\ufff6\023\ufff6\001\002\000\006\010\264\023" +
    "\265\001\002\000\004\044\266\001\002\000\006\007\ufff8" +
    "\013\ufff8\001\002\000\006\010\ufff7\023\ufff7\001\002\000" +
    "\004\044\270\001\002\000\004\010\271\001\002\000\004" +
    "\044\272\001\002\000\004\010\273\001\002\000\004\042" +
    "\274\001\002\000\004\010\275\001\002\000\004\022\231" +
    "\001\002\000\004\010\277\001\002\000\004\044\300\001" +
    "\002\000\006\007\uffe8\013\uffe8\001\002\000\004\044\302" +
    "\001\002\000\004\010\303\001\002\000\004\044\304\001" +
    "\002\000\004\010\305\001\002\000\004\044\306\001\002" +
    "\000\004\010\307\001\002\000\004\044\310\001\002\000" +
    "\004\007\311\001\002\000\004\004\uffd6\001\002\000\004" +
    "\044\313\001\002\000\004\010\314\001\002\000\004\044" +
    "\315\001\002\000\004\010\316\001\002\000\004\044\317" +
    "\001\002\000\004\010\320\001\002\000\004\044\321\001" +
    "\002\000\004\010\322\001\002\000\004\040\323\001\002" +
    "\000\004\007\324\001\002\000\004\004\uffcc\001\002\000" +
    "\004\044\326\001\002\000\004\010\327\001\002\000\004" +
    "\044\330\001\002\000\004\010\331\001\002\000\004\042" +
    "\332\001\002\000\006\007\uffe0\013\uffe0\001\002\000\004" +
    "\013\334\001\002\000\004\015\335\001\002\000\004\007" +
    "\336\001\002\000\004\004\uffcf\001\002\000\004\007\347" +
    "\001\002\000\004\004\ufff0\001\002\000\004\004\013\001" +
    "\002\000\004\004\343\001\002\000\004\013\344\001\002" +
    "\000\004\032\345\001\002\000\004\007\346\001\002\000" +
    "\004\004\uffed\001\002\000\004\004\uffee\001\002\000\004" +
    "\007\360\001\002\000\004\004\ufff4\001\002\000\004\004" +
    "\013\001\002\000\004\004\354\001\002\000\004\013\355" +
    "\001\002\000\004\024\356\001\002\000\004\007\357\001" +
    "\002\000\004\004\ufff1\001\002\000\004\004\ufff2\001\002" +
    "\000\006\013\363\015\136\001\002\000\004\004\uffd1\001" +
    "\002\000\004\021\364\001\002\000\004\007\365\001\002" +
    "\000\004\004\uffd2\001\002\000\004\004\uffd4\001\002\000" +
    "\006\013\370\021\131\001\002\000\004\012\371\001\002" +
    "\000\004\007\372\001\002\000\004\004\uffd5\001\002\000" +
    "\006\002\uffd7\004\uffd7\001\002\000\004\013\375\001\002" +
    "\000\004\035\376\001\002\000\004\007\377\001\002\000" +
    "\006\002\uffce\004\uffce\001\002\000\004\004\u0101\001\002" +
    "\000\004\012\u0108\001\002\000\004\004\u0104\001\002\000" +
    "\006\002\uffcd\004\uffcd\001\002\000\004\013\u0105\001\002" +
    "\000\004\031\u0106\001\002\000\004\007\u0107\001\002\000" +
    "\006\002\uffca\004\uffca\001\002\000\004\007\u0109\001\002" +
    "\000\004\004\145\001\002\000\004\004\u010d\001\002\000" +
    "\004\004\uffdc\001\002\000\004\004\uffdd\001\002\000\022" +
    "\013\u010e\014\215\024\216\025\217\030\212\031\213\032" +
    "\220\035\214\001\002\000\004\012\u010f\001\002\000\004" +
    "\007\u0110\001\002\000\004\004\uffcb\001\002\000\006\002" +
    "\uffff\004\uffff\001\002\000\004\002\001\001\002\000\006" +
    "\002\000\004\000\001\002" });

  /** Access to parse-action table. */
  public short[][] action_table() {return _action_table;}

  /** <code>reduce_goto</code> table. */
  protected static final short[][] _reduce_table = 
    unpackFromStrings(new String[] {
    "\000\u0111\000\014\004\003\013\007\014\004\015\005\033" +
    "\010\001\001\000\012\013\u0112\014\u0110\015\005\033\010" +
    "\001\001\000\002\001\001\000\004\042\377\001\001\000" +
    "\002\001\001\000\002\001\001\000\004\042\011\001\001" +
    "\000\004\012\121\001\001\000\002\001\001\000\002\001" +
    "\001\000\006\041\017\044\015\001\001\000\004\045\071" +
    "\001\001\000\002\001\001\000\002\001\001\000\004\054" +
    "\022\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\004\043\036\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\004\043\066\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\004" +
    "\046\101\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\004\043\076\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\004\053\111\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\004\002\372" +
    "\001\001\000\002\001\001\000\002\001\001\000\006\007" +
    "\125\011\126\001\001\000\002\001\001\000\004\007\365" +
    "\001\001\000\002\001\001\000\002\001\001\000\006\006" +
    "\132\032\134\001\001\000\004\032\361\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\042\013" +
    "\140\014\143\015\005\016\145\017\151\020\147\021\153" +
    "\022\146\023\154\024\137\025\141\026\152\027\155\030" +
    "\150\031\142\033\010\001\001\000\004\034\350\001\001" +
    "\000\002\001\001\000\004\035\337\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\004\040\200\001" +
    "\001\000\002\001\001\000\004\036\170\001\001\000\002" +
    "\001\001\000\002\001\001\000\004\037\156\001\001\000" +
    "\002\001\001\000\002\001\001\000\004\042\161\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\004\042\172\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\004\042\203\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\004\051\227" +
    "\001\001\000\002\001\001\000\004\052\232\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\004\051" +
    "\255\001\001\000\002\001\001\000\004\047\260\001\001" +
    "\000\004\050\262\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\004\051\275\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\004\042\341\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\004\042\352\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\004\010\u0101\001\001\000\002\001\001" +
    "\000\004\003\u0102\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\044\005\u0109\013\140\014\143\015" +
    "\005\016\145\017\151\020\147\021\153\022\146\023\154" +
    "\024\137\025\141\026\152\027\155\030\150\031\u010a\033" +
    "\010\001\001\000\042\013\140\014\143\015\005\016\145" +
    "\017\151\020\147\021\153\022\146\023\154\024\137\025" +
    "\141\026\152\027\155\030\150\031\u010b\033\010\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001" });

  /** Access to <code>reduce_goto</code> table. */
  public short[][] reduce_table() {return _reduce_table;}

  /** Instance of action encapsulation class. */
  protected CUP$PkmParser$actions action_obj;

  /** Action encapsulation object initializer. */
  protected void init_actions()
    {
      action_obj = new CUP$PkmParser$actions(this);
    }

  /** Invoke a user supplied parse action. */
  public java_cup.runtime.Symbol do_action(
    int                        act_num,
    java_cup.runtime.lr_parser parser,
    java.util.Stack            stack,
    int                        top)
    throws java.lang.Exception
  {
    /* call code in generated class */
    return action_obj.CUP$PkmParser$do_action(act_num, parser, stack, top);
  }

  /** Indicates start state. */
  public int start_state() {return 0;}
  /** Indicates start production. */
  public int start_production() {return 0;}

  /** <code>EOF</code> Symbol index. */
  public int EOF_sym() {return 0;}

  /** <code>error</code> Symbol index. */
  public int error_sym() {return 1;}



	private ConversorColores conversor = new ConversorColores();
	
	public PkmParser(PkmLexer lex){
        super(lex);
    }

    public void syntax_error(Symbol cur_token){
        Log.w("MI_APP", "Warning" + cur_token.left + " " + cur_token.right);
        throw new PkmException();
    }

    public void report_error(String message, Object info){
        throw new PkmException();
    }

    public void unrecovered_syntax_error(Symbol cur_token){
        throw new PkmException();
    }


/** Cup generated class to encapsulate user supplied action code.*/
@SuppressWarnings({"rawtypes", "unchecked", "unused"})
class CUP$PkmParser$actions {
  private final PkmParser parser;

  /** Constructor */
  CUP$PkmParser$actions(PkmParser parser) {
    this.parser = parser;
  }

  /** Method 0 with the actual generated action code for actions 0 to 300. */
  public final java_cup.runtime.Symbol CUP$PkmParser$do_action_part00000000(
    int                        CUP$PkmParser$act_num,
    java_cup.runtime.lr_parser CUP$PkmParser$parser,
    java.util.Stack            CUP$PkmParser$stack,
    int                        CUP$PkmParser$top)
    throws java.lang.Exception
    {
      /* Symbol object for return from actions */
      java_cup.runtime.Symbol CUP$PkmParser$result;

      /* select the action based on the action number */
      switch (CUP$PkmParser$act_num)
        {
          /*. . . . . . . . . . . . . . . . . . . .*/
          case 0: // $START ::= formulario EOF 
            {
              Object RESULT =null;
		int start_valleft = ((java_cup.runtime.Symbol)CUP$PkmParser$stack.elementAt(CUP$PkmParser$top-1)).left;
		int start_valright = ((java_cup.runtime.Symbol)CUP$PkmParser$stack.elementAt(CUP$PkmParser$top-1)).right;
		LinkedList<Nodoui> start_val = (LinkedList<Nodoui>)((java_cup.runtime.Symbol) CUP$PkmParser$stack.elementAt(CUP$PkmParser$top-1)).value;
		RESULT = start_val;
              CUP$PkmParser$result = parser.getSymbolFactory().newSymbol("$START",0, ((java_cup.runtime.Symbol)CUP$PkmParser$stack.elementAt(CUP$PkmParser$top-1)), ((java_cup.runtime.Symbol)CUP$PkmParser$stack.peek()), RESULT);
            }
          /* ACCEPT */
          CUP$PkmParser$parser.done_parsing();
          return CUP$PkmParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 1: // formulario ::= formulario tabla 
            {
              LinkedList<Nodoui> RESULT =null;
		int n1left = ((java_cup.runtime.Symbol)CUP$PkmParser$stack.elementAt(CUP$PkmParser$top-1)).left;
		int n1right = ((java_cup.runtime.Symbol)CUP$PkmParser$stack.elementAt(CUP$PkmParser$top-1)).right;
		LinkedList<Nodoui> n1 = (LinkedList<Nodoui>)((java_cup.runtime.Symbol) CUP$PkmParser$stack.elementAt(CUP$PkmParser$top-1)).value;
		int n2left = ((java_cup.runtime.Symbol)CUP$PkmParser$stack.peek()).left;
		int n2right = ((java_cup.runtime.Symbol)CUP$PkmParser$stack.peek()).right;
		Nodoui n2 = (Nodoui)((java_cup.runtime.Symbol) CUP$PkmParser$stack.peek()).value;
		 RESULT = n1; n1.add(n2); 
              CUP$PkmParser$result = parser.getSymbolFactory().newSymbol("formulario",2, ((java_cup.runtime.Symbol)CUP$PkmParser$stack.elementAt(CUP$PkmParser$top-1)), ((java_cup.runtime.Symbol)CUP$PkmParser$stack.peek()), RESULT);
            }
          return CUP$PkmParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 2: // formulario ::= formulario seccion 
            {
              LinkedList<Nodoui> RESULT =null;
		int n1left = ((java_cup.runtime.Symbol)CUP$PkmParser$stack.elementAt(CUP$PkmParser$top-1)).left;
		int n1right = ((java_cup.runtime.Symbol)CUP$PkmParser$stack.elementAt(CUP$PkmParser$top-1)).right;
		LinkedList<Nodoui> n1 = (LinkedList<Nodoui>)((java_cup.runtime.Symbol) CUP$PkmParser$stack.elementAt(CUP$PkmParser$top-1)).value;
		int n2left = ((java_cup.runtime.Symbol)CUP$PkmParser$stack.peek()).left;
		int n2right = ((java_cup.runtime.Symbol)CUP$PkmParser$stack.peek()).right;
		Nodoui n2 = (Nodoui)((java_cup.runtime.Symbol) CUP$PkmParser$stack.peek()).value;
		 RESULT = n1; n1.add(n2); 
              CUP$PkmParser$result = parser.getSymbolFactory().newSymbol("formulario",2, ((java_cup.runtime.Symbol)CUP$PkmParser$stack.elementAt(CUP$PkmParser$top-1)), ((java_cup.runtime.Symbol)CUP$PkmParser$stack.peek()), RESULT);
            }
          return CUP$PkmParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 3: // formulario ::= tabla 
            {
              LinkedList<Nodoui> RESULT =null;
		int n1left = ((java_cup.runtime.Symbol)CUP$PkmParser$stack.peek()).left;
		int n1right = ((java_cup.runtime.Symbol)CUP$PkmParser$stack.peek()).right;
		Nodoui n1 = (Nodoui)((java_cup.runtime.Symbol) CUP$PkmParser$stack.peek()).value;
		 RESULT = new LinkedList<Nodoui>(); RESULT.add(n1); 
              CUP$PkmParser$result = parser.getSymbolFactory().newSymbol("formulario",2, ((java_cup.runtime.Symbol)CUP$PkmParser$stack.peek()), ((java_cup.runtime.Symbol)CUP$PkmParser$stack.peek()), RESULT);
            }
          return CUP$PkmParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 4: // formulario ::= seccion 
            {
              LinkedList<Nodoui> RESULT =null;
		int n1left = ((java_cup.runtime.Symbol)CUP$PkmParser$stack.peek()).left;
		int n1right = ((java_cup.runtime.Symbol)CUP$PkmParser$stack.peek()).right;
		Nodoui n1 = (Nodoui)((java_cup.runtime.Symbol) CUP$PkmParser$stack.peek()).value;
		 RESULT = new LinkedList<Nodoui>(); RESULT.add(n1); 
              CUP$PkmParser$result = parser.getSymbolFactory().newSymbol("formulario",2, ((java_cup.runtime.Symbol)CUP$PkmParser$stack.peek()), ((java_cup.runtime.Symbol)CUP$PkmParser$stack.peek()), RESULT);
            }
          return CUP$PkmParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 5: // pregunta ::= pregunta_abierta 
            {
              Nodoui RESULT =null;
		int n1left = ((java_cup.runtime.Symbol)CUP$PkmParser$stack.peek()).left;
		int n1right = ((java_cup.runtime.Symbol)CUP$PkmParser$stack.peek()).right;
		Nodoui n1 = (Nodoui)((java_cup.runtime.Symbol) CUP$PkmParser$stack.peek()).value;
		 RESULT = n1; 
              CUP$PkmParser$result = parser.getSymbolFactory().newSymbol("pregunta",13, ((java_cup.runtime.Symbol)CUP$PkmParser$stack.peek()), ((java_cup.runtime.Symbol)CUP$PkmParser$stack.peek()), RESULT);
            }
          return CUP$PkmParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 6: // pregunta ::= pregunta_multiple 
            {
              Nodoui RESULT =null;
		int n1left = ((java_cup.runtime.Symbol)CUP$PkmParser$stack.peek()).left;
		int n1right = ((java_cup.runtime.Symbol)CUP$PkmParser$stack.peek()).right;
		Nodoui n1 = (Nodoui)((java_cup.runtime.Symbol) CUP$PkmParser$stack.peek()).value;
		 RESULT = n1; 
              CUP$PkmParser$result = parser.getSymbolFactory().newSymbol("pregunta",13, ((java_cup.runtime.Symbol)CUP$PkmParser$stack.peek()), ((java_cup.runtime.Symbol)CUP$PkmParser$stack.peek()), RESULT);
            }
          return CUP$PkmParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 7: // pregunta ::= pregunta_select 
            {
              Nodoui RESULT =null;
		int n1left = ((java_cup.runtime.Symbol)CUP$PkmParser$stack.peek()).left;
		int n1right = ((java_cup.runtime.Symbol)CUP$PkmParser$stack.peek()).right;
		Nodoui n1 = (Nodoui)((java_cup.runtime.Symbol) CUP$PkmParser$stack.peek()).value;
		 RESULT = n1; 
              CUP$PkmParser$result = parser.getSymbolFactory().newSymbol("pregunta",13, ((java_cup.runtime.Symbol)CUP$PkmParser$stack.peek()), ((java_cup.runtime.Symbol)CUP$PkmParser$stack.peek()), RESULT);
            }
          return CUP$PkmParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 8: // pregunta ::= pregunta_drop 
            {
              Nodoui RESULT =null;
		int n1left = ((java_cup.runtime.Symbol)CUP$PkmParser$stack.peek()).left;
		int n1right = ((java_cup.runtime.Symbol)CUP$PkmParser$stack.peek()).right;
		Nodoui n1 = (Nodoui)((java_cup.runtime.Symbol) CUP$PkmParser$stack.peek()).value;
		 RESULT = n1; 
              CUP$PkmParser$result = parser.getSymbolFactory().newSymbol("pregunta",13, ((java_cup.runtime.Symbol)CUP$PkmParser$stack.peek()), ((java_cup.runtime.Symbol)CUP$PkmParser$stack.peek()), RESULT);
            }
          return CUP$PkmParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 9: // lista_correct ::= LLAVEAPER numeros LLAVECERRA 
            {
              List<Double> RESULT =null;
		int n2left = ((java_cup.runtime.Symbol)CUP$PkmParser$stack.elementAt(CUP$PkmParser$top-1)).left;
		int n2right = ((java_cup.runtime.Symbol)CUP$PkmParser$stack.elementAt(CUP$PkmParser$top-1)).right;
		List<Double> n2 = (List<Double>)((java_cup.runtime.Symbol) CUP$PkmParser$stack.elementAt(CUP$PkmParser$top-1)).value;
		 RESULT = n2; 
              CUP$PkmParser$result = parser.getSymbolFactory().newSymbol("lista_correct",37, ((java_cup.runtime.Symbol)CUP$PkmParser$stack.elementAt(CUP$PkmParser$top-2)), ((java_cup.runtime.Symbol)CUP$PkmParser$stack.peek()), RESULT);
            }
          return CUP$PkmParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 10: // numeros ::= numeros COMA NUMERO 
            {
              List<Double> RESULT =null;
		int n1left = ((java_cup.runtime.Symbol)CUP$PkmParser$stack.elementAt(CUP$PkmParser$top-2)).left;
		int n1right = ((java_cup.runtime.Symbol)CUP$PkmParser$stack.elementAt(CUP$PkmParser$top-2)).right;
		List<Double> n1 = (List<Double>)((java_cup.runtime.Symbol) CUP$PkmParser$stack.elementAt(CUP$PkmParser$top-2)).value;
		int n3left = ((java_cup.runtime.Symbol)CUP$PkmParser$stack.peek()).left;
		int n3right = ((java_cup.runtime.Symbol)CUP$PkmParser$stack.peek()).right;
		Double n3 = (Double)((java_cup.runtime.Symbol) CUP$PkmParser$stack.peek()).value;
		 RESULT = n1; n1.add(n3); 
              CUP$PkmParser$result = parser.getSymbolFactory().newSymbol("numeros",38, ((java_cup.runtime.Symbol)CUP$PkmParser$stack.elementAt(CUP$PkmParser$top-2)), ((java_cup.runtime.Symbol)CUP$PkmParser$stack.peek()), RESULT);
            }
          return CUP$PkmParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 11: // numeros ::= NUMERO 
            {
              List<Double> RESULT =null;
		int n1left = ((java_cup.runtime.Symbol)CUP$PkmParser$stack.peek()).left;
		int n1right = ((java_cup.runtime.Symbol)CUP$PkmParser$stack.peek()).right;
		Double n1 = (Double)((java_cup.runtime.Symbol) CUP$PkmParser$stack.peek()).value;
		 RESULT = new LinkedList<Double>(); RESULT.add(n1); 
              CUP$PkmParser$result = parser.getSymbolFactory().newSymbol("numeros",38, ((java_cup.runtime.Symbol)CUP$PkmParser$stack.peek()), ((java_cup.runtime.Symbol)CUP$PkmParser$stack.peek()), RESULT);
            }
          return CUP$PkmParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 12: // numeros ::= 
            {
              List<Double> RESULT =null;
		 RESULT = new LinkedList<Double>(); 
              CUP$PkmParser$result = parser.getSymbolFactory().newSymbol("numeros",38, ((java_cup.runtime.Symbol)CUP$PkmParser$stack.peek()), RESULT);
            }
          return CUP$PkmParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 13: // pregunta_multiple ::= pregmul_aper pregmul_final 
            {
              Nodoui RESULT =null;
		int n1left = ((java_cup.runtime.Symbol)CUP$PkmParser$stack.elementAt(CUP$PkmParser$top-1)).left;
		int n1right = ((java_cup.runtime.Symbol)CUP$PkmParser$stack.elementAt(CUP$PkmParser$top-1)).right;
		Nodoui n1 = (Nodoui)((java_cup.runtime.Symbol) CUP$PkmParser$stack.elementAt(CUP$PkmParser$top-1)).value;
		int n2left = ((java_cup.runtime.Symbol)CUP$PkmParser$stack.peek()).left;
		int n2right = ((java_cup.runtime.Symbol)CUP$PkmParser$stack.peek()).right;
		Estiloui n2 = (Estiloui)((java_cup.runtime.Symbol) CUP$PkmParser$stack.peek()).value;
		 RESULT = n1; n1.setEstilo(n2); 
              CUP$PkmParser$result = parser.getSymbolFactory().newSymbol("pregunta_multiple",16, ((java_cup.runtime.Symbol)CUP$PkmParser$stack.elementAt(CUP$PkmParser$top-1)), ((java_cup.runtime.Symbol)CUP$PkmParser$stack.peek()), RESULT);
            }
          return CUP$PkmParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 14: // pregmul_aper ::= APERT MULTIPLE IGUAL NUMERO COMA NUMERO COMA CADENA COMA lista_op COMA lista_correct 
            {
              Nodoui RESULT =null;
		int n4left = ((java_cup.runtime.Symbol)CUP$PkmParser$stack.elementAt(CUP$PkmParser$top-8)).left;
		int n4right = ((java_cup.runtime.Symbol)CUP$PkmParser$stack.elementAt(CUP$PkmParser$top-8)).right;
		Double n4 = (Double)((java_cup.runtime.Symbol) CUP$PkmParser$stack.elementAt(CUP$PkmParser$top-8)).value;
		int n6left = ((java_cup.runtime.Symbol)CUP$PkmParser$stack.elementAt(CUP$PkmParser$top-6)).left;
		int n6right = ((java_cup.runtime.Symbol)CUP$PkmParser$stack.elementAt(CUP$PkmParser$top-6)).right;
		Double n6 = (Double)((java_cup.runtime.Symbol) CUP$PkmParser$stack.elementAt(CUP$PkmParser$top-6)).value;
		int n8left = ((java_cup.runtime.Symbol)CUP$PkmParser$stack.elementAt(CUP$PkmParser$top-4)).left;
		int n8right = ((java_cup.runtime.Symbol)CUP$PkmParser$stack.elementAt(CUP$PkmParser$top-4)).right;
		String n8 = (String)((java_cup.runtime.Symbol) CUP$PkmParser$stack.elementAt(CUP$PkmParser$top-4)).value;
		int n10left = ((java_cup.runtime.Symbol)CUP$PkmParser$stack.elementAt(CUP$PkmParser$top-2)).left;
		int n10right = ((java_cup.runtime.Symbol)CUP$PkmParser$stack.elementAt(CUP$PkmParser$top-2)).right;
		List<String> n10 = (List<String>)((java_cup.runtime.Symbol) CUP$PkmParser$stack.elementAt(CUP$PkmParser$top-2)).value;
		int n12left = ((java_cup.runtime.Symbol)CUP$PkmParser$stack.peek()).left;
		int n12right = ((java_cup.runtime.Symbol)CUP$PkmParser$stack.peek()).right;
		List<Double> n12 = (List<Double>)((java_cup.runtime.Symbol) CUP$PkmParser$stack.peek()).value;
		 RESULT = new PreguntaMultiple(n4, n6, n8, n10, n12); 
              CUP$PkmParser$result = parser.getSymbolFactory().newSymbol("pregmul_aper",18, ((java_cup.runtime.Symbol)CUP$PkmParser$stack.elementAt(CUP$PkmParser$top-11)), ((java_cup.runtime.Symbol)CUP$PkmParser$stack.peek()), RESULT);
            }
          return CUP$PkmParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 15: // pregmul_final ::= DIAGON CERRA 
            {
              Estiloui RESULT =null;

              CUP$PkmParser$result = parser.getSymbolFactory().newSymbol("pregmul_final",26, ((java_cup.runtime.Symbol)CUP$PkmParser$stack.elementAt(CUP$PkmParser$top-1)), ((java_cup.runtime.Symbol)CUP$PkmParser$stack.peek()), RESULT);
            }
          return CUP$PkmParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 16: // pregmul_final ::= CERRA estilo APERT DIAGON MULTIPLE CERRA 
            {
              Estiloui RESULT =null;
		int n2left = ((java_cup.runtime.Symbol)CUP$PkmParser$stack.elementAt(CUP$PkmParser$top-4)).left;
		int n2right = ((java_cup.runtime.Symbol)CUP$PkmParser$stack.elementAt(CUP$PkmParser$top-4)).right;
		Estiloui n2 = (Estiloui)((java_cup.runtime.Symbol) CUP$PkmParser$stack.elementAt(CUP$PkmParser$top-4)).value;
		 RESULT = n2; 
              CUP$PkmParser$result = parser.getSymbolFactory().newSymbol("pregmul_final",26, ((java_cup.runtime.Symbol)CUP$PkmParser$stack.elementAt(CUP$PkmParser$top-5)), ((java_cup.runtime.Symbol)CUP$PkmParser$stack.peek()), RESULT);
            }
          return CUP$PkmParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 17: // pregunta_select ::= pregsel_aper pregsel_final 
            {
              Nodoui RESULT =null;
		int n1left = ((java_cup.runtime.Symbol)CUP$PkmParser$stack.elementAt(CUP$PkmParser$top-1)).left;
		int n1right = ((java_cup.runtime.Symbol)CUP$PkmParser$stack.elementAt(CUP$PkmParser$top-1)).right;
		Nodoui n1 = (Nodoui)((java_cup.runtime.Symbol) CUP$PkmParser$stack.elementAt(CUP$PkmParser$top-1)).value;
		int n2left = ((java_cup.runtime.Symbol)CUP$PkmParser$stack.peek()).left;
		int n2right = ((java_cup.runtime.Symbol)CUP$PkmParser$stack.peek()).right;
		Estiloui n2 = (Estiloui)((java_cup.runtime.Symbol) CUP$PkmParser$stack.peek()).value;
		 RESULT = n1; n1.setEstilo(n2); 
              CUP$PkmParser$result = parser.getSymbolFactory().newSymbol("pregunta_select",17, ((java_cup.runtime.Symbol)CUP$PkmParser$stack.elementAt(CUP$PkmParser$top-1)), ((java_cup.runtime.Symbol)CUP$PkmParser$stack.peek()), RESULT);
            }
          return CUP$PkmParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 18: // pregsel_aper ::= APERT SELECT IGUAL NUMERO COMA NUMERO COMA CADENA COMA lista_op COMA NUMERO 
            {
              Nodoui RESULT =null;
		int n4left = ((java_cup.runtime.Symbol)CUP$PkmParser$stack.elementAt(CUP$PkmParser$top-8)).left;
		int n4right = ((java_cup.runtime.Symbol)CUP$PkmParser$stack.elementAt(CUP$PkmParser$top-8)).right;
		Double n4 = (Double)((java_cup.runtime.Symbol) CUP$PkmParser$stack.elementAt(CUP$PkmParser$top-8)).value;
		int n6left = ((java_cup.runtime.Symbol)CUP$PkmParser$stack.elementAt(CUP$PkmParser$top-6)).left;
		int n6right = ((java_cup.runtime.Symbol)CUP$PkmParser$stack.elementAt(CUP$PkmParser$top-6)).right;
		Double n6 = (Double)((java_cup.runtime.Symbol) CUP$PkmParser$stack.elementAt(CUP$PkmParser$top-6)).value;
		int n8left = ((java_cup.runtime.Symbol)CUP$PkmParser$stack.elementAt(CUP$PkmParser$top-4)).left;
		int n8right = ((java_cup.runtime.Symbol)CUP$PkmParser$stack.elementAt(CUP$PkmParser$top-4)).right;
		String n8 = (String)((java_cup.runtime.Symbol) CUP$PkmParser$stack.elementAt(CUP$PkmParser$top-4)).value;
		int n10left = ((java_cup.runtime.Symbol)CUP$PkmParser$stack.elementAt(CUP$PkmParser$top-2)).left;
		int n10right = ((java_cup.runtime.Symbol)CUP$PkmParser$stack.elementAt(CUP$PkmParser$top-2)).right;
		List<String> n10 = (List<String>)((java_cup.runtime.Symbol) CUP$PkmParser$stack.elementAt(CUP$PkmParser$top-2)).value;
		int n12left = ((java_cup.runtime.Symbol)CUP$PkmParser$stack.peek()).left;
		int n12right = ((java_cup.runtime.Symbol)CUP$PkmParser$stack.peek()).right;
		Double n12 = (Double)((java_cup.runtime.Symbol) CUP$PkmParser$stack.peek()).value;
		 RESULT = new PreguntaSeleccion(n4, n6, n8, n10, n12); 
              CUP$PkmParser$result = parser.getSymbolFactory().newSymbol("pregsel_aper",19, ((java_cup.runtime.Symbol)CUP$PkmParser$stack.elementAt(CUP$PkmParser$top-11)), ((java_cup.runtime.Symbol)CUP$PkmParser$stack.peek()), RESULT);
            }
          return CUP$PkmParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 19: // pregsel_final ::= DIAGON CERRA 
            {
              Estiloui RESULT =null;

              CUP$PkmParser$result = parser.getSymbolFactory().newSymbol("pregsel_final",27, ((java_cup.runtime.Symbol)CUP$PkmParser$stack.elementAt(CUP$PkmParser$top-1)), ((java_cup.runtime.Symbol)CUP$PkmParser$stack.peek()), RESULT);
            }
          return CUP$PkmParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 20: // pregsel_final ::= CERRA estilo APERT DIAGON SELECT CERRA 
            {
              Estiloui RESULT =null;
		int n2left = ((java_cup.runtime.Symbol)CUP$PkmParser$stack.elementAt(CUP$PkmParser$top-4)).left;
		int n2right = ((java_cup.runtime.Symbol)CUP$PkmParser$stack.elementAt(CUP$PkmParser$top-4)).right;
		Estiloui n2 = (Estiloui)((java_cup.runtime.Symbol) CUP$PkmParser$stack.elementAt(CUP$PkmParser$top-4)).value;
		 RESULT = n2; 
              CUP$PkmParser$result = parser.getSymbolFactory().newSymbol("pregsel_final",27, ((java_cup.runtime.Symbol)CUP$PkmParser$stack.elementAt(CUP$PkmParser$top-5)), ((java_cup.runtime.Symbol)CUP$PkmParser$stack.peek()), RESULT);
            }
          return CUP$PkmParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 21: // lista_op ::= LLAVEAPER opciones LLAVECERRA 
            {
              List<String> RESULT =null;
		int n2left = ((java_cup.runtime.Symbol)CUP$PkmParser$stack.elementAt(CUP$PkmParser$top-1)).left;
		int n2right = ((java_cup.runtime.Symbol)CUP$PkmParser$stack.elementAt(CUP$PkmParser$top-1)).right;
		List<String> n2 = (List<String>)((java_cup.runtime.Symbol) CUP$PkmParser$stack.elementAt(CUP$PkmParser$top-1)).value;
		 RESULT = n2; 
              CUP$PkmParser$result = parser.getSymbolFactory().newSymbol("lista_op",39, ((java_cup.runtime.Symbol)CUP$PkmParser$stack.elementAt(CUP$PkmParser$top-2)), ((java_cup.runtime.Symbol)CUP$PkmParser$stack.peek()), RESULT);
            }
          return CUP$PkmParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 22: // opciones ::= opciones COMA CADENA 
            {
              List<String> RESULT =null;
		int n1left = ((java_cup.runtime.Symbol)CUP$PkmParser$stack.elementAt(CUP$PkmParser$top-2)).left;
		int n1right = ((java_cup.runtime.Symbol)CUP$PkmParser$stack.elementAt(CUP$PkmParser$top-2)).right;
		List<String> n1 = (List<String>)((java_cup.runtime.Symbol) CUP$PkmParser$stack.elementAt(CUP$PkmParser$top-2)).value;
		int n3left = ((java_cup.runtime.Symbol)CUP$PkmParser$stack.peek()).left;
		int n3right = ((java_cup.runtime.Symbol)CUP$PkmParser$stack.peek()).right;
		String n3 = (String)((java_cup.runtime.Symbol) CUP$PkmParser$stack.peek()).value;
		 RESULT = n1; n1.add(n3); 
              CUP$PkmParser$result = parser.getSymbolFactory().newSymbol("opciones",40, ((java_cup.runtime.Symbol)CUP$PkmParser$stack.elementAt(CUP$PkmParser$top-2)), ((java_cup.runtime.Symbol)CUP$PkmParser$stack.peek()), RESULT);
            }
          return CUP$PkmParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 23: // opciones ::= CADENA 
            {
              List<String> RESULT =null;
		int n1left = ((java_cup.runtime.Symbol)CUP$PkmParser$stack.peek()).left;
		int n1right = ((java_cup.runtime.Symbol)CUP$PkmParser$stack.peek()).right;
		String n1 = (String)((java_cup.runtime.Symbol) CUP$PkmParser$stack.peek()).value;
		 RESULT = new LinkedList<String>(); RESULT.add(n1); 
              CUP$PkmParser$result = parser.getSymbolFactory().newSymbol("opciones",40, ((java_cup.runtime.Symbol)CUP$PkmParser$stack.peek()), ((java_cup.runtime.Symbol)CUP$PkmParser$stack.peek()), RESULT);
            }
          return CUP$PkmParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 24: // pregunta_drop ::= predrop_aper predrop_final 
            {
              Nodoui RESULT =null;
		int n1left = ((java_cup.runtime.Symbol)CUP$PkmParser$stack.elementAt(CUP$PkmParser$top-1)).left;
		int n1right = ((java_cup.runtime.Symbol)CUP$PkmParser$stack.elementAt(CUP$PkmParser$top-1)).right;
		Nodoui n1 = (Nodoui)((java_cup.runtime.Symbol) CUP$PkmParser$stack.elementAt(CUP$PkmParser$top-1)).value;
		int n2left = ((java_cup.runtime.Symbol)CUP$PkmParser$stack.peek()).left;
		int n2right = ((java_cup.runtime.Symbol)CUP$PkmParser$stack.peek()).right;
		Estiloui n2 = (Estiloui)((java_cup.runtime.Symbol) CUP$PkmParser$stack.peek()).value;
		 RESULT = n1; n1.setEstilo(n2); 
              CUP$PkmParser$result = parser.getSymbolFactory().newSymbol("pregunta_drop",15, ((java_cup.runtime.Symbol)CUP$PkmParser$stack.elementAt(CUP$PkmParser$top-1)), ((java_cup.runtime.Symbol)CUP$PkmParser$stack.peek()), RESULT);
            }
          return CUP$PkmParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 25: // predrop_aper ::= APERT DROP IGUAL NUMERO COMA NUMERO COMA CADENA COMA lista_op COMA NUMERO 
            {
              Nodoui RESULT =null;
		int n4left = ((java_cup.runtime.Symbol)CUP$PkmParser$stack.elementAt(CUP$PkmParser$top-8)).left;
		int n4right = ((java_cup.runtime.Symbol)CUP$PkmParser$stack.elementAt(CUP$PkmParser$top-8)).right;
		Double n4 = (Double)((java_cup.runtime.Symbol) CUP$PkmParser$stack.elementAt(CUP$PkmParser$top-8)).value;
		int n6left = ((java_cup.runtime.Symbol)CUP$PkmParser$stack.elementAt(CUP$PkmParser$top-6)).left;
		int n6right = ((java_cup.runtime.Symbol)CUP$PkmParser$stack.elementAt(CUP$PkmParser$top-6)).right;
		Double n6 = (Double)((java_cup.runtime.Symbol) CUP$PkmParser$stack.elementAt(CUP$PkmParser$top-6)).value;
		int n7left = ((java_cup.runtime.Symbol)CUP$PkmParser$stack.elementAt(CUP$PkmParser$top-4)).left;
		int n7right = ((java_cup.runtime.Symbol)CUP$PkmParser$stack.elementAt(CUP$PkmParser$top-4)).right;
		String n7 = (String)((java_cup.runtime.Symbol) CUP$PkmParser$stack.elementAt(CUP$PkmParser$top-4)).value;
		int n9left = ((java_cup.runtime.Symbol)CUP$PkmParser$stack.elementAt(CUP$PkmParser$top-2)).left;
		int n9right = ((java_cup.runtime.Symbol)CUP$PkmParser$stack.elementAt(CUP$PkmParser$top-2)).right;
		List<String> n9 = (List<String>)((java_cup.runtime.Symbol) CUP$PkmParser$stack.elementAt(CUP$PkmParser$top-2)).value;
		int n11left = ((java_cup.runtime.Symbol)CUP$PkmParser$stack.peek()).left;
		int n11right = ((java_cup.runtime.Symbol)CUP$PkmParser$stack.peek()).right;
		Double n11 = (Double)((java_cup.runtime.Symbol) CUP$PkmParser$stack.peek()).value;
		 RESULT = new PreguntaDesplegable(n4, n6, n7, n9, n11); 
              CUP$PkmParser$result = parser.getSymbolFactory().newSymbol("predrop_aper",20, ((java_cup.runtime.Symbol)CUP$PkmParser$stack.elementAt(CUP$PkmParser$top-11)), ((java_cup.runtime.Symbol)CUP$PkmParser$stack.peek()), RESULT);
            }
          return CUP$PkmParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 26: // predrop_final ::= DIAGON CERRA 
            {
              Estiloui RESULT =null;

              CUP$PkmParser$result = parser.getSymbolFactory().newSymbol("predrop_final",28, ((java_cup.runtime.Symbol)CUP$PkmParser$stack.elementAt(CUP$PkmParser$top-1)), ((java_cup.runtime.Symbol)CUP$PkmParser$stack.peek()), RESULT);
            }
          return CUP$PkmParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 27: // predrop_final ::= CERRA estilo APERT DIAGON DROP CERRA 
            {
              Estiloui RESULT =null;
		int n2left = ((java_cup.runtime.Symbol)CUP$PkmParser$stack.elementAt(CUP$PkmParser$top-4)).left;
		int n2right = ((java_cup.runtime.Symbol)CUP$PkmParser$stack.elementAt(CUP$PkmParser$top-4)).right;
		Estiloui n2 = (Estiloui)((java_cup.runtime.Symbol) CUP$PkmParser$stack.elementAt(CUP$PkmParser$top-4)).value;
		 RESULT = n2; 
              CUP$PkmParser$result = parser.getSymbolFactory().newSymbol("predrop_final",28, ((java_cup.runtime.Symbol)CUP$PkmParser$stack.elementAt(CUP$PkmParser$top-5)), ((java_cup.runtime.Symbol)CUP$PkmParser$stack.peek()), RESULT);
            }
          return CUP$PkmParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 28: // pregunta_abierta ::= preabier_aper preabier_final 
            {
              Nodoui RESULT =null;
		int n1left = ((java_cup.runtime.Symbol)CUP$PkmParser$stack.elementAt(CUP$PkmParser$top-1)).left;
		int n1right = ((java_cup.runtime.Symbol)CUP$PkmParser$stack.elementAt(CUP$PkmParser$top-1)).right;
		Nodoui n1 = (Nodoui)((java_cup.runtime.Symbol) CUP$PkmParser$stack.elementAt(CUP$PkmParser$top-1)).value;
		int n2left = ((java_cup.runtime.Symbol)CUP$PkmParser$stack.peek()).left;
		int n2right = ((java_cup.runtime.Symbol)CUP$PkmParser$stack.peek()).right;
		Estiloui n2 = (Estiloui)((java_cup.runtime.Symbol) CUP$PkmParser$stack.peek()).value;
		 RESULT = n1; n1.setEstilo(n2); 
              CUP$PkmParser$result = parser.getSymbolFactory().newSymbol("pregunta_abierta",14, ((java_cup.runtime.Symbol)CUP$PkmParser$stack.elementAt(CUP$PkmParser$top-1)), ((java_cup.runtime.Symbol)CUP$PkmParser$stack.peek()), RESULT);
            }
          return CUP$PkmParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 29: // preabier_aper ::= APERT OPEN IGUAL NUMERO COMA NUMERO COMA CADENA 
            {
              Nodoui RESULT =null;
		int n4left = ((java_cup.runtime.Symbol)CUP$PkmParser$stack.elementAt(CUP$PkmParser$top-4)).left;
		int n4right = ((java_cup.runtime.Symbol)CUP$PkmParser$stack.elementAt(CUP$PkmParser$top-4)).right;
		Double n4 = (Double)((java_cup.runtime.Symbol) CUP$PkmParser$stack.elementAt(CUP$PkmParser$top-4)).value;
		int n6left = ((java_cup.runtime.Symbol)CUP$PkmParser$stack.elementAt(CUP$PkmParser$top-2)).left;
		int n6right = ((java_cup.runtime.Symbol)CUP$PkmParser$stack.elementAt(CUP$PkmParser$top-2)).right;
		Double n6 = (Double)((java_cup.runtime.Symbol) CUP$PkmParser$stack.elementAt(CUP$PkmParser$top-2)).value;
		int n8left = ((java_cup.runtime.Symbol)CUP$PkmParser$stack.peek()).left;
		int n8right = ((java_cup.runtime.Symbol)CUP$PkmParser$stack.peek()).right;
		String n8 = (String)((java_cup.runtime.Symbol) CUP$PkmParser$stack.peek()).value;
		 RESULT = new PreguntaAbierta(n4, n6, n8); 
              CUP$PkmParser$result = parser.getSymbolFactory().newSymbol("preabier_aper",21, ((java_cup.runtime.Symbol)CUP$PkmParser$stack.elementAt(CUP$PkmParser$top-7)), ((java_cup.runtime.Symbol)CUP$PkmParser$stack.peek()), RESULT);
            }
          return CUP$PkmParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 30: // preabier_final ::= DIAGON CERRA 
            {
              Estiloui RESULT =null;

              CUP$PkmParser$result = parser.getSymbolFactory().newSymbol("preabier_final",29, ((java_cup.runtime.Symbol)CUP$PkmParser$stack.elementAt(CUP$PkmParser$top-1)), ((java_cup.runtime.Symbol)CUP$PkmParser$stack.peek()), RESULT);
            }
          return CUP$PkmParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 31: // preabier_final ::= CERRA estilo APERT DIAGON OPEN CERRA 
            {
              Estiloui RESULT =null;
		int n2left = ((java_cup.runtime.Symbol)CUP$PkmParser$stack.elementAt(CUP$PkmParser$top-4)).left;
		int n2right = ((java_cup.runtime.Symbol)CUP$PkmParser$stack.elementAt(CUP$PkmParser$top-4)).right;
		Estiloui n2 = (Estiloui)((java_cup.runtime.Symbol) CUP$PkmParser$stack.elementAt(CUP$PkmParser$top-4)).value;
		 RESULT = n2; 
              CUP$PkmParser$result = parser.getSymbolFactory().newSymbol("preabier_final",29, ((java_cup.runtime.Symbol)CUP$PkmParser$stack.elementAt(CUP$PkmParser$top-5)), ((java_cup.runtime.Symbol)CUP$PkmParser$stack.peek()), RESULT);
            }
          return CUP$PkmParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 32: // texto ::= texto_aper texto_final 
            {
              Nodoui RESULT =null;
		int n1left = ((java_cup.runtime.Symbol)CUP$PkmParser$stack.elementAt(CUP$PkmParser$top-1)).left;
		int n1right = ((java_cup.runtime.Symbol)CUP$PkmParser$stack.elementAt(CUP$PkmParser$top-1)).right;
		Nodoui n1 = (Nodoui)((java_cup.runtime.Symbol) CUP$PkmParser$stack.elementAt(CUP$PkmParser$top-1)).value;
		int n2left = ((java_cup.runtime.Symbol)CUP$PkmParser$stack.peek()).left;
		int n2right = ((java_cup.runtime.Symbol)CUP$PkmParser$stack.peek()).right;
		Estiloui n2 = (Estiloui)((java_cup.runtime.Symbol) CUP$PkmParser$stack.peek()).value;
		 RESULT = n1; n1.setEstilo(n2); 
              CUP$PkmParser$result = parser.getSymbolFactory().newSymbol("texto",12, ((java_cup.runtime.Symbol)CUP$PkmParser$stack.elementAt(CUP$PkmParser$top-1)), ((java_cup.runtime.Symbol)CUP$PkmParser$stack.peek()), RESULT);
            }
          return CUP$PkmParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 33: // texto_aper ::= APERT TEXT IGUAL NUMERO COMA NUMERO COMA CADENA 
            {
              Nodoui RESULT =null;
		int n4left = ((java_cup.runtime.Symbol)CUP$PkmParser$stack.elementAt(CUP$PkmParser$top-4)).left;
		int n4right = ((java_cup.runtime.Symbol)CUP$PkmParser$stack.elementAt(CUP$PkmParser$top-4)).right;
		Double n4 = (Double)((java_cup.runtime.Symbol) CUP$PkmParser$stack.elementAt(CUP$PkmParser$top-4)).value;
		int n6left = ((java_cup.runtime.Symbol)CUP$PkmParser$stack.elementAt(CUP$PkmParser$top-2)).left;
		int n6right = ((java_cup.runtime.Symbol)CUP$PkmParser$stack.elementAt(CUP$PkmParser$top-2)).right;
		Double n6 = (Double)((java_cup.runtime.Symbol) CUP$PkmParser$stack.elementAt(CUP$PkmParser$top-2)).value;
		int n8left = ((java_cup.runtime.Symbol)CUP$PkmParser$stack.peek()).left;
		int n8right = ((java_cup.runtime.Symbol)CUP$PkmParser$stack.peek()).right;
		String n8 = (String)((java_cup.runtime.Symbol) CUP$PkmParser$stack.peek()).value;
		 RESULT = new Texto(n4, n6, n8); 
              CUP$PkmParser$result = parser.getSymbolFactory().newSymbol("texto_aper",22, ((java_cup.runtime.Symbol)CUP$PkmParser$stack.elementAt(CUP$PkmParser$top-7)), ((java_cup.runtime.Symbol)CUP$PkmParser$stack.peek()), RESULT);
            }
          return CUP$PkmParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 34: // texto_final ::= DIAGON CERRA 
            {
              Estiloui RESULT =null;

              CUP$PkmParser$result = parser.getSymbolFactory().newSymbol("texto_final",30, ((java_cup.runtime.Symbol)CUP$PkmParser$stack.elementAt(CUP$PkmParser$top-1)), ((java_cup.runtime.Symbol)CUP$PkmParser$stack.peek()), RESULT);
            }
          return CUP$PkmParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 35: // texto_final ::= CERRA estilo APERT DIAGON TEXT CERRA 
            {
              Estiloui RESULT =null;
		int n2left = ((java_cup.runtime.Symbol)CUP$PkmParser$stack.elementAt(CUP$PkmParser$top-4)).left;
		int n2right = ((java_cup.runtime.Symbol)CUP$PkmParser$stack.elementAt(CUP$PkmParser$top-4)).right;
		Estiloui n2 = (Estiloui)((java_cup.runtime.Symbol) CUP$PkmParser$stack.elementAt(CUP$PkmParser$top-4)).value;
		 RESULT = n2; 
              CUP$PkmParser$result = parser.getSymbolFactory().newSymbol("texto_final",30, ((java_cup.runtime.Symbol)CUP$PkmParser$stack.elementAt(CUP$PkmParser$top-5)), ((java_cup.runtime.Symbol)CUP$PkmParser$stack.peek()), RESULT);
            }
          return CUP$PkmParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 36: // elementos ::= elementos elemento 
            {
              LinkedList<Nodoui> RESULT =null;
		int n1left = ((java_cup.runtime.Symbol)CUP$PkmParser$stack.elementAt(CUP$PkmParser$top-1)).left;
		int n1right = ((java_cup.runtime.Symbol)CUP$PkmParser$stack.elementAt(CUP$PkmParser$top-1)).right;
		LinkedList<Nodoui> n1 = (LinkedList<Nodoui>)((java_cup.runtime.Symbol) CUP$PkmParser$stack.elementAt(CUP$PkmParser$top-1)).value;
		int n2left = ((java_cup.runtime.Symbol)CUP$PkmParser$stack.peek()).left;
		int n2right = ((java_cup.runtime.Symbol)CUP$PkmParser$stack.peek()).right;
		Nodoui n2 = (Nodoui)((java_cup.runtime.Symbol) CUP$PkmParser$stack.peek()).value;
		 RESULT = n1; n1.add(n2); 
              CUP$PkmParser$result = parser.getSymbolFactory().newSymbol("elementos",3, ((java_cup.runtime.Symbol)CUP$PkmParser$stack.elementAt(CUP$PkmParser$top-1)), ((java_cup.runtime.Symbol)CUP$PkmParser$stack.peek()), RESULT);
            }
          return CUP$PkmParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 37: // elementos ::= elemento 
            {
              LinkedList<Nodoui> RESULT =null;
		int n1left = ((java_cup.runtime.Symbol)CUP$PkmParser$stack.peek()).left;
		int n1right = ((java_cup.runtime.Symbol)CUP$PkmParser$stack.peek()).right;
		Nodoui n1 = (Nodoui)((java_cup.runtime.Symbol) CUP$PkmParser$stack.peek()).value;
		 RESULT = new LinkedList<Nodoui>(); RESULT.add(n1); 
              CUP$PkmParser$result = parser.getSymbolFactory().newSymbol("elementos",3, ((java_cup.runtime.Symbol)CUP$PkmParser$stack.peek()), ((java_cup.runtime.Symbol)CUP$PkmParser$stack.peek()), RESULT);
            }
          return CUP$PkmParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 38: // elemento ::= tabla 
            {
              Nodoui RESULT =null;
		int n1left = ((java_cup.runtime.Symbol)CUP$PkmParser$stack.peek()).left;
		int n1right = ((java_cup.runtime.Symbol)CUP$PkmParser$stack.peek()).right;
		Nodoui n1 = (Nodoui)((java_cup.runtime.Symbol) CUP$PkmParser$stack.peek()).value;
		 RESULT = n1; 
              CUP$PkmParser$result = parser.getSymbolFactory().newSymbol("elemento",23, ((java_cup.runtime.Symbol)CUP$PkmParser$stack.peek()), ((java_cup.runtime.Symbol)CUP$PkmParser$stack.peek()), RESULT);
            }
          return CUP$PkmParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 39: // elemento ::= seccion 
            {
              Nodoui RESULT =null;
		int n1left = ((java_cup.runtime.Symbol)CUP$PkmParser$stack.peek()).left;
		int n1right = ((java_cup.runtime.Symbol)CUP$PkmParser$stack.peek()).right;
		Nodoui n1 = (Nodoui)((java_cup.runtime.Symbol) CUP$PkmParser$stack.peek()).value;
		 RESULT = n1; 
              CUP$PkmParser$result = parser.getSymbolFactory().newSymbol("elemento",23, ((java_cup.runtime.Symbol)CUP$PkmParser$stack.peek()), ((java_cup.runtime.Symbol)CUP$PkmParser$stack.peek()), RESULT);
            }
          return CUP$PkmParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 40: // elemento ::= pregunta 
            {
              Nodoui RESULT =null;
		int n1left = ((java_cup.runtime.Symbol)CUP$PkmParser$stack.peek()).left;
		int n1right = ((java_cup.runtime.Symbol)CUP$PkmParser$stack.peek()).right;
		Nodoui n1 = (Nodoui)((java_cup.runtime.Symbol) CUP$PkmParser$stack.peek()).value;
		 RESULT = n1; 
              CUP$PkmParser$result = parser.getSymbolFactory().newSymbol("elemento",23, ((java_cup.runtime.Symbol)CUP$PkmParser$stack.peek()), ((java_cup.runtime.Symbol)CUP$PkmParser$stack.peek()), RESULT);
            }
          return CUP$PkmParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 41: // elemento ::= texto 
            {
              Nodoui RESULT =null;
		int n1left = ((java_cup.runtime.Symbol)CUP$PkmParser$stack.peek()).left;
		int n1right = ((java_cup.runtime.Symbol)CUP$PkmParser$stack.peek()).right;
		Nodoui n1 = (Nodoui)((java_cup.runtime.Symbol) CUP$PkmParser$stack.peek()).value;
		 RESULT = n1; 
              CUP$PkmParser$result = parser.getSymbolFactory().newSymbol("elemento",23, ((java_cup.runtime.Symbol)CUP$PkmParser$stack.peek()), ((java_cup.runtime.Symbol)CUP$PkmParser$stack.peek()), RESULT);
            }
          return CUP$PkmParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 42: // tabla ::= tabla_aper estilo contenido_tabla tabla_cerra 
            {
              Nodoui RESULT =null;
		int n1left = ((java_cup.runtime.Symbol)CUP$PkmParser$stack.elementAt(CUP$PkmParser$top-3)).left;
		int n1right = ((java_cup.runtime.Symbol)CUP$PkmParser$stack.elementAt(CUP$PkmParser$top-3)).right;
		Nodoui n1 = (Nodoui)((java_cup.runtime.Symbol) CUP$PkmParser$stack.elementAt(CUP$PkmParser$top-3)).value;
		int n2left = ((java_cup.runtime.Symbol)CUP$PkmParser$stack.elementAt(CUP$PkmParser$top-2)).left;
		int n2right = ((java_cup.runtime.Symbol)CUP$PkmParser$stack.elementAt(CUP$PkmParser$top-2)).right;
		Estiloui n2 = (Estiloui)((java_cup.runtime.Symbol) CUP$PkmParser$stack.elementAt(CUP$PkmParser$top-2)).value;
		int n3left = ((java_cup.runtime.Symbol)CUP$PkmParser$stack.elementAt(CUP$PkmParser$top-1)).left;
		int n3right = ((java_cup.runtime.Symbol)CUP$PkmParser$stack.elementAt(CUP$PkmParser$top-1)).right;
		List<LinkedList<Nodoui>> n3 = (List<LinkedList<Nodoui>>)((java_cup.runtime.Symbol) CUP$PkmParser$stack.elementAt(CUP$PkmParser$top-1)).value;
		 RESULT = n1; n1.setEstilo(n2); ((Tabla)n1).agregarElementos(n3); 
              CUP$PkmParser$result = parser.getSymbolFactory().newSymbol("tabla",9, ((java_cup.runtime.Symbol)CUP$PkmParser$stack.elementAt(CUP$PkmParser$top-3)), ((java_cup.runtime.Symbol)CUP$PkmParser$stack.peek()), RESULT);
            }
          return CUP$PkmParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 43: // tabla_aper ::= APERT TABLE IGUAL NUMERO COMA NUMERO COMA NUMERO COMA NUMERO CERRA 
            {
              Nodoui RESULT =null;
		int n3left = ((java_cup.runtime.Symbol)CUP$PkmParser$stack.elementAt(CUP$PkmParser$top-7)).left;
		int n3right = ((java_cup.runtime.Symbol)CUP$PkmParser$stack.elementAt(CUP$PkmParser$top-7)).right;
		Double n3 = (Double)((java_cup.runtime.Symbol) CUP$PkmParser$stack.elementAt(CUP$PkmParser$top-7)).value;
		int n5left = ((java_cup.runtime.Symbol)CUP$PkmParser$stack.elementAt(CUP$PkmParser$top-5)).left;
		int n5right = ((java_cup.runtime.Symbol)CUP$PkmParser$stack.elementAt(CUP$PkmParser$top-5)).right;
		Double n5 = (Double)((java_cup.runtime.Symbol) CUP$PkmParser$stack.elementAt(CUP$PkmParser$top-5)).value;
		int n7left = ((java_cup.runtime.Symbol)CUP$PkmParser$stack.elementAt(CUP$PkmParser$top-3)).left;
		int n7right = ((java_cup.runtime.Symbol)CUP$PkmParser$stack.elementAt(CUP$PkmParser$top-3)).right;
		Double n7 = (Double)((java_cup.runtime.Symbol) CUP$PkmParser$stack.elementAt(CUP$PkmParser$top-3)).value;
		int n9left = ((java_cup.runtime.Symbol)CUP$PkmParser$stack.elementAt(CUP$PkmParser$top-1)).left;
		int n9right = ((java_cup.runtime.Symbol)CUP$PkmParser$stack.elementAt(CUP$PkmParser$top-1)).right;
		Double n9 = (Double)((java_cup.runtime.Symbol) CUP$PkmParser$stack.elementAt(CUP$PkmParser$top-1)).value;
		 RESULT = new Tabla(n3, n5, n7, n9); 
              CUP$PkmParser$result = parser.getSymbolFactory().newSymbol("tabla_aper",25, ((java_cup.runtime.Symbol)CUP$PkmParser$stack.elementAt(CUP$PkmParser$top-10)), ((java_cup.runtime.Symbol)CUP$PkmParser$stack.peek()), RESULT);
            }
          return CUP$PkmParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 44: // contenido_tabla ::= APERT CONTENT CERRA columnas_tabla APERT DIAGON CONTENT CERRA 
            {
              List<LinkedList<Nodoui>> RESULT =null;
		int n4left = ((java_cup.runtime.Symbol)CUP$PkmParser$stack.elementAt(CUP$PkmParser$top-4)).left;
		int n4right = ((java_cup.runtime.Symbol)CUP$PkmParser$stack.elementAt(CUP$PkmParser$top-4)).right;
		List<LinkedList<Nodoui>> n4 = (List<LinkedList<Nodoui>>)((java_cup.runtime.Symbol) CUP$PkmParser$stack.elementAt(CUP$PkmParser$top-4)).value;
		 RESULT = n4; 
              CUP$PkmParser$result = parser.getSymbolFactory().newSymbol("contenido_tabla",8, ((java_cup.runtime.Symbol)CUP$PkmParser$stack.elementAt(CUP$PkmParser$top-7)), ((java_cup.runtime.Symbol)CUP$PkmParser$stack.peek()), RESULT);
            }
          return CUP$PkmParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 45: // columnas_tabla ::= columnas_tabla columna_tabla 
            {
              List<LinkedList<Nodoui>> RESULT =null;
		int n1left = ((java_cup.runtime.Symbol)CUP$PkmParser$stack.elementAt(CUP$PkmParser$top-1)).left;
		int n1right = ((java_cup.runtime.Symbol)CUP$PkmParser$stack.elementAt(CUP$PkmParser$top-1)).right;
		List<LinkedList<Nodoui>> n1 = (List<LinkedList<Nodoui>>)((java_cup.runtime.Symbol) CUP$PkmParser$stack.elementAt(CUP$PkmParser$top-1)).value;
		int n2left = ((java_cup.runtime.Symbol)CUP$PkmParser$stack.peek()).left;
		int n2right = ((java_cup.runtime.Symbol)CUP$PkmParser$stack.peek()).right;
		LinkedList<Nodoui> n2 = (LinkedList<Nodoui>)((java_cup.runtime.Symbol) CUP$PkmParser$stack.peek()).value;
		 RESULT = n1; n1.add(n2); 
              CUP$PkmParser$result = parser.getSymbolFactory().newSymbol("columnas_tabla",7, ((java_cup.runtime.Symbol)CUP$PkmParser$stack.elementAt(CUP$PkmParser$top-1)), ((java_cup.runtime.Symbol)CUP$PkmParser$stack.peek()), RESULT);
            }
          return CUP$PkmParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 46: // columnas_tabla ::= columna_tabla 
            {
              List<LinkedList<Nodoui>> RESULT =null;
		int n1left = ((java_cup.runtime.Symbol)CUP$PkmParser$stack.peek()).left;
		int n1right = ((java_cup.runtime.Symbol)CUP$PkmParser$stack.peek()).right;
		LinkedList<Nodoui> n1 = (LinkedList<Nodoui>)((java_cup.runtime.Symbol) CUP$PkmParser$stack.peek()).value;
		 RESULT = new LinkedList<LinkedList<Nodoui>>(); RESULT.add(n1); 
              CUP$PkmParser$result = parser.getSymbolFactory().newSymbol("columnas_tabla",7, ((java_cup.runtime.Symbol)CUP$PkmParser$stack.peek()), ((java_cup.runtime.Symbol)CUP$PkmParser$stack.peek()), RESULT);
            }
          return CUP$PkmParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 47: // columna_tabla ::= APERT LINE CERRA filas_tabla APERT DIAGON LINE CERRA 
            {
              LinkedList<Nodoui> RESULT =null;
		int n4left = ((java_cup.runtime.Symbol)CUP$PkmParser$stack.elementAt(CUP$PkmParser$top-4)).left;
		int n4right = ((java_cup.runtime.Symbol)CUP$PkmParser$stack.elementAt(CUP$PkmParser$top-4)).right;
		LinkedList<Nodoui> n4 = (LinkedList<Nodoui>)((java_cup.runtime.Symbol) CUP$PkmParser$stack.elementAt(CUP$PkmParser$top-4)).value;
		 RESULT = n4; 
              CUP$PkmParser$result = parser.getSymbolFactory().newSymbol("columna_tabla",5, ((java_cup.runtime.Symbol)CUP$PkmParser$stack.elementAt(CUP$PkmParser$top-7)), ((java_cup.runtime.Symbol)CUP$PkmParser$stack.peek()), RESULT);
            }
          return CUP$PkmParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 48: // filas_tabla ::= filas_tabla fila_tabla 
            {
              LinkedList<Nodoui> RESULT =null;
		int n1left = ((java_cup.runtime.Symbol)CUP$PkmParser$stack.elementAt(CUP$PkmParser$top-1)).left;
		int n1right = ((java_cup.runtime.Symbol)CUP$PkmParser$stack.elementAt(CUP$PkmParser$top-1)).right;
		LinkedList<Nodoui> n1 = (LinkedList<Nodoui>)((java_cup.runtime.Symbol) CUP$PkmParser$stack.elementAt(CUP$PkmParser$top-1)).value;
		int n2left = ((java_cup.runtime.Symbol)CUP$PkmParser$stack.peek()).left;
		int n2right = ((java_cup.runtime.Symbol)CUP$PkmParser$stack.peek()).right;
		Nodoui n2 = (Nodoui)((java_cup.runtime.Symbol) CUP$PkmParser$stack.peek()).value;
		 RESULT = n1; n1.add(n2); 
              CUP$PkmParser$result = parser.getSymbolFactory().newSymbol("filas_tabla",4, ((java_cup.runtime.Symbol)CUP$PkmParser$stack.elementAt(CUP$PkmParser$top-1)), ((java_cup.runtime.Symbol)CUP$PkmParser$stack.peek()), RESULT);
            }
          return CUP$PkmParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 49: // filas_tabla ::= fila_tabla 
            {
              LinkedList<Nodoui> RESULT =null;
		int n1left = ((java_cup.runtime.Symbol)CUP$PkmParser$stack.peek()).left;
		int n1right = ((java_cup.runtime.Symbol)CUP$PkmParser$stack.peek()).right;
		Nodoui n1 = (Nodoui)((java_cup.runtime.Symbol) CUP$PkmParser$stack.peek()).value;
		 RESULT = new LinkedList<Nodoui>(); RESULT.add(n1); 
              CUP$PkmParser$result = parser.getSymbolFactory().newSymbol("filas_tabla",4, ((java_cup.runtime.Symbol)CUP$PkmParser$stack.peek()), ((java_cup.runtime.Symbol)CUP$PkmParser$stack.peek()), RESULT);
            }
          return CUP$PkmParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 50: // fila_tabla ::= APERT ELEMENT CERRA elemento APERT DIAGON ELEMENT CERRA 
            {
              Nodoui RESULT =null;
		int n4left = ((java_cup.runtime.Symbol)CUP$PkmParser$stack.elementAt(CUP$PkmParser$top-4)).left;
		int n4right = ((java_cup.runtime.Symbol)CUP$PkmParser$stack.elementAt(CUP$PkmParser$top-4)).right;
		Nodoui n4 = (Nodoui)((java_cup.runtime.Symbol) CUP$PkmParser$stack.elementAt(CUP$PkmParser$top-4)).value;
		 RESULT = n4; 
              CUP$PkmParser$result = parser.getSymbolFactory().newSymbol("fila_tabla",24, ((java_cup.runtime.Symbol)CUP$PkmParser$stack.elementAt(CUP$PkmParser$top-7)), ((java_cup.runtime.Symbol)CUP$PkmParser$stack.peek()), RESULT);
            }
          return CUP$PkmParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 51: // tabla_cerra ::= APERT DIAGON TABLE CERRA 
            {
              Object RESULT =null;

              CUP$PkmParser$result = parser.getSymbolFactory().newSymbol("tabla_cerra",0, ((java_cup.runtime.Symbol)CUP$PkmParser$stack.elementAt(CUP$PkmParser$top-3)), ((java_cup.runtime.Symbol)CUP$PkmParser$stack.peek()), RESULT);
            }
          return CUP$PkmParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 52: // seccion ::= seccion_aper estilo elementos_sec seccion_cerra 
            {
              Nodoui RESULT =null;
		int n1left = ((java_cup.runtime.Symbol)CUP$PkmParser$stack.elementAt(CUP$PkmParser$top-3)).left;
		int n1right = ((java_cup.runtime.Symbol)CUP$PkmParser$stack.elementAt(CUP$PkmParser$top-3)).right;
		Nodoui n1 = (Nodoui)((java_cup.runtime.Symbol) CUP$PkmParser$stack.elementAt(CUP$PkmParser$top-3)).value;
		int n2left = ((java_cup.runtime.Symbol)CUP$PkmParser$stack.elementAt(CUP$PkmParser$top-2)).left;
		int n2right = ((java_cup.runtime.Symbol)CUP$PkmParser$stack.elementAt(CUP$PkmParser$top-2)).right;
		Estiloui n2 = (Estiloui)((java_cup.runtime.Symbol) CUP$PkmParser$stack.elementAt(CUP$PkmParser$top-2)).value;
		int n3left = ((java_cup.runtime.Symbol)CUP$PkmParser$stack.elementAt(CUP$PkmParser$top-1)).left;
		int n3right = ((java_cup.runtime.Symbol)CUP$PkmParser$stack.elementAt(CUP$PkmParser$top-1)).right;
		LinkedList<Nodoui> n3 = (LinkedList<Nodoui>)((java_cup.runtime.Symbol) CUP$PkmParser$stack.elementAt(CUP$PkmParser$top-1)).value;
		 RESULT = n1; ((Seccion)n1).agregarLista(n3); n1.setEstilo(n2); 
              CUP$PkmParser$result = parser.getSymbolFactory().newSymbol("seccion",10, ((java_cup.runtime.Symbol)CUP$PkmParser$stack.elementAt(CUP$PkmParser$top-3)), ((java_cup.runtime.Symbol)CUP$PkmParser$stack.peek()), RESULT);
            }
          return CUP$PkmParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 53: // seccion_aper ::= APERT SECTION IGUAL NUMERO COMA NUMERO COMA NUMERO COMA NUMERO COMA ORIENTACION CERRA 
            {
              Nodoui RESULT =null;
		int n4left = ((java_cup.runtime.Symbol)CUP$PkmParser$stack.elementAt(CUP$PkmParser$top-9)).left;
		int n4right = ((java_cup.runtime.Symbol)CUP$PkmParser$stack.elementAt(CUP$PkmParser$top-9)).right;
		Double n4 = (Double)((java_cup.runtime.Symbol) CUP$PkmParser$stack.elementAt(CUP$PkmParser$top-9)).value;
		int n6left = ((java_cup.runtime.Symbol)CUP$PkmParser$stack.elementAt(CUP$PkmParser$top-7)).left;
		int n6right = ((java_cup.runtime.Symbol)CUP$PkmParser$stack.elementAt(CUP$PkmParser$top-7)).right;
		Double n6 = (Double)((java_cup.runtime.Symbol) CUP$PkmParser$stack.elementAt(CUP$PkmParser$top-7)).value;
		int n8left = ((java_cup.runtime.Symbol)CUP$PkmParser$stack.elementAt(CUP$PkmParser$top-5)).left;
		int n8right = ((java_cup.runtime.Symbol)CUP$PkmParser$stack.elementAt(CUP$PkmParser$top-5)).right;
		Double n8 = (Double)((java_cup.runtime.Symbol) CUP$PkmParser$stack.elementAt(CUP$PkmParser$top-5)).value;
		int n10left = ((java_cup.runtime.Symbol)CUP$PkmParser$stack.elementAt(CUP$PkmParser$top-3)).left;
		int n10right = ((java_cup.runtime.Symbol)CUP$PkmParser$stack.elementAt(CUP$PkmParser$top-3)).right;
		Double n10 = (Double)((java_cup.runtime.Symbol) CUP$PkmParser$stack.elementAt(CUP$PkmParser$top-3)).value;
		int n12left = ((java_cup.runtime.Symbol)CUP$PkmParser$stack.elementAt(CUP$PkmParser$top-1)).left;
		int n12right = ((java_cup.runtime.Symbol)CUP$PkmParser$stack.elementAt(CUP$PkmParser$top-1)).right;
		Orientacion n12 = (Orientacion)((java_cup.runtime.Symbol) CUP$PkmParser$stack.elementAt(CUP$PkmParser$top-1)).value;
		 RESULT = new Seccion(n4, n6, n8, n10, n12); 
              CUP$PkmParser$result = parser.getSymbolFactory().newSymbol("seccion_aper",11, ((java_cup.runtime.Symbol)CUP$PkmParser$stack.elementAt(CUP$PkmParser$top-12)), ((java_cup.runtime.Symbol)CUP$PkmParser$stack.peek()), RESULT);
            }
          return CUP$PkmParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 54: // elementos_sec ::= APERT CONTENT CERRA elementos APERT DIAGON CONTENT CERRA 
            {
              LinkedList<Nodoui> RESULT =null;
		int n4left = ((java_cup.runtime.Symbol)CUP$PkmParser$stack.elementAt(CUP$PkmParser$top-4)).left;
		int n4right = ((java_cup.runtime.Symbol)CUP$PkmParser$stack.elementAt(CUP$PkmParser$top-4)).right;
		LinkedList<Nodoui> n4 = (LinkedList<Nodoui>)((java_cup.runtime.Symbol) CUP$PkmParser$stack.elementAt(CUP$PkmParser$top-4)).value;
		 RESULT = n4; 
              CUP$PkmParser$result = parser.getSymbolFactory().newSymbol("elementos_sec",6, ((java_cup.runtime.Symbol)CUP$PkmParser$stack.elementAt(CUP$PkmParser$top-7)), ((java_cup.runtime.Symbol)CUP$PkmParser$stack.peek()), RESULT);
            }
          return CUP$PkmParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 55: // seccion_cerra ::= APERT DIAGON SECTION CERRA 
            {
              Object RESULT =null;

              CUP$PkmParser$result = parser.getSymbolFactory().newSymbol("seccion_cerra",1, ((java_cup.runtime.Symbol)CUP$PkmParser$stack.elementAt(CUP$PkmParser$top-3)), ((java_cup.runtime.Symbol)CUP$PkmParser$stack.peek()), RESULT);
            }
          return CUP$PkmParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 56: // estilo ::= APERT STYLE CERRA estilos APERT border 
            {
              Estiloui RESULT =null;
		int n4left = ((java_cup.runtime.Symbol)CUP$PkmParser$stack.elementAt(CUP$PkmParser$top-2)).left;
		int n4right = ((java_cup.runtime.Symbol)CUP$PkmParser$stack.elementAt(CUP$PkmParser$top-2)).right;
		Estiloui n4 = (Estiloui)((java_cup.runtime.Symbol) CUP$PkmParser$stack.elementAt(CUP$PkmParser$top-2)).value;
		int n6left = ((java_cup.runtime.Symbol)CUP$PkmParser$stack.peek()).left;
		int n6right = ((java_cup.runtime.Symbol)CUP$PkmParser$stack.peek()).right;
		Border n6 = (Border)((java_cup.runtime.Symbol) CUP$PkmParser$stack.peek()).value;
		 RESULT = n4; n4.setBorder(n6); 
              CUP$PkmParser$result = parser.getSymbolFactory().newSymbol("estilo",32, ((java_cup.runtime.Symbol)CUP$PkmParser$stack.elementAt(CUP$PkmParser$top-5)), ((java_cup.runtime.Symbol)CUP$PkmParser$stack.peek()), RESULT);
            }
          return CUP$PkmParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 57: // estilos ::= color_a background font text_size 
            {
              Estiloui RESULT =null;
		int n1left = ((java_cup.runtime.Symbol)CUP$PkmParser$stack.elementAt(CUP$PkmParser$top-3)).left;
		int n1right = ((java_cup.runtime.Symbol)CUP$PkmParser$stack.elementAt(CUP$PkmParser$top-3)).right;
		ClaseColor n1 = (ClaseColor)((java_cup.runtime.Symbol) CUP$PkmParser$stack.elementAt(CUP$PkmParser$top-3)).value;
		int n2left = ((java_cup.runtime.Symbol)CUP$PkmParser$stack.elementAt(CUP$PkmParser$top-2)).left;
		int n2right = ((java_cup.runtime.Symbol)CUP$PkmParser$stack.elementAt(CUP$PkmParser$top-2)).right;
		ClaseColor n2 = (ClaseColor)((java_cup.runtime.Symbol) CUP$PkmParser$stack.elementAt(CUP$PkmParser$top-2)).value;
		int n3left = ((java_cup.runtime.Symbol)CUP$PkmParser$stack.elementAt(CUP$PkmParser$top-1)).left;
		int n3right = ((java_cup.runtime.Symbol)CUP$PkmParser$stack.elementAt(CUP$PkmParser$top-1)).right;
		TLetra n3 = (TLetra)((java_cup.runtime.Symbol) CUP$PkmParser$stack.elementAt(CUP$PkmParser$top-1)).value;
		int n4left = ((java_cup.runtime.Symbol)CUP$PkmParser$stack.peek()).left;
		int n4right = ((java_cup.runtime.Symbol)CUP$PkmParser$stack.peek()).right;
		Double n4 = (Double)((java_cup.runtime.Symbol) CUP$PkmParser$stack.peek()).value;
		 RESULT = new Estiloui(n1, n2, n3, n4); 
              CUP$PkmParser$result = parser.getSymbolFactory().newSymbol("estilos",31, ((java_cup.runtime.Symbol)CUP$PkmParser$stack.elementAt(CUP$PkmParser$top-3)), ((java_cup.runtime.Symbol)CUP$PkmParser$stack.peek()), RESULT);
            }
          return CUP$PkmParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 58: // color_a ::= APERT COLOR IGUAL color DIAGON CERRA 
            {
              ClaseColor RESULT =null;
		int n4left = ((java_cup.runtime.Symbol)CUP$PkmParser$stack.elementAt(CUP$PkmParser$top-2)).left;
		int n4right = ((java_cup.runtime.Symbol)CUP$PkmParser$stack.elementAt(CUP$PkmParser$top-2)).right;
		ClaseColor n4 = (ClaseColor)((java_cup.runtime.Symbol) CUP$PkmParser$stack.elementAt(CUP$PkmParser$top-2)).value;
		 RESULT = n4; 
              CUP$PkmParser$result = parser.getSymbolFactory().newSymbol("color_a",34, ((java_cup.runtime.Symbol)CUP$PkmParser$stack.elementAt(CUP$PkmParser$top-5)), ((java_cup.runtime.Symbol)CUP$PkmParser$stack.peek()), RESULT);
            }
          return CUP$PkmParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 59: // background ::= APERT BACKGROUND COLOR IGUAL color DIAGON CERRA 
            {
              ClaseColor RESULT =null;
		int n5left = ((java_cup.runtime.Symbol)CUP$PkmParser$stack.elementAt(CUP$PkmParser$top-2)).left;
		int n5right = ((java_cup.runtime.Symbol)CUP$PkmParser$stack.elementAt(CUP$PkmParser$top-2)).right;
		ClaseColor n5 = (ClaseColor)((java_cup.runtime.Symbol) CUP$PkmParser$stack.elementAt(CUP$PkmParser$top-2)).value;
		 RESULT = n5; 
              CUP$PkmParser$result = parser.getSymbolFactory().newSymbol("background",35, ((java_cup.runtime.Symbol)CUP$PkmParser$stack.elementAt(CUP$PkmParser$top-6)), ((java_cup.runtime.Symbol)CUP$PkmParser$stack.peek()), RESULT);
            }
          return CUP$PkmParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 60: // font ::= APERT FONT FAMILY IGUAL TLETRA DIAGON CERRA 
            {
              TLetra RESULT =null;
		int n5left = ((java_cup.runtime.Symbol)CUP$PkmParser$stack.elementAt(CUP$PkmParser$top-2)).left;
		int n5right = ((java_cup.runtime.Symbol)CUP$PkmParser$stack.elementAt(CUP$PkmParser$top-2)).right;
		TLetra n5 = (TLetra)((java_cup.runtime.Symbol) CUP$PkmParser$stack.elementAt(CUP$PkmParser$top-2)).value;
		 RESULT = n5; 
              CUP$PkmParser$result = parser.getSymbolFactory().newSymbol("font",36, ((java_cup.runtime.Symbol)CUP$PkmParser$stack.elementAt(CUP$PkmParser$top-6)), ((java_cup.runtime.Symbol)CUP$PkmParser$stack.peek()), RESULT);
            }
          return CUP$PkmParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 61: // text_size ::= APERT TEXT SIZE IGUAL NUMERO DIAGON CERRA 
            {
              Double RESULT =null;
		int n5left = ((java_cup.runtime.Symbol)CUP$PkmParser$stack.elementAt(CUP$PkmParser$top-2)).left;
		int n5right = ((java_cup.runtime.Symbol)CUP$PkmParser$stack.elementAt(CUP$PkmParser$top-2)).right;
		Double n5 = (Double)((java_cup.runtime.Symbol) CUP$PkmParser$stack.elementAt(CUP$PkmParser$top-2)).value;
		 RESULT = n5; 
              CUP$PkmParser$result = parser.getSymbolFactory().newSymbol("text_size",41, ((java_cup.runtime.Symbol)CUP$PkmParser$stack.elementAt(CUP$PkmParser$top-6)), ((java_cup.runtime.Symbol)CUP$PkmParser$stack.peek()), RESULT);
            }
          return CUP$PkmParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 62: // border ::= BORDER COMA NUMERO COMA TBORDE COMA COLOR IGUAL color DIAGON CERRA APERT DIAGON STYLE CERRA 
            {
              Border RESULT =null;
		int n4left = ((java_cup.runtime.Symbol)CUP$PkmParser$stack.elementAt(CUP$PkmParser$top-12)).left;
		int n4right = ((java_cup.runtime.Symbol)CUP$PkmParser$stack.elementAt(CUP$PkmParser$top-12)).right;
		Double n4 = (Double)((java_cup.runtime.Symbol) CUP$PkmParser$stack.elementAt(CUP$PkmParser$top-12)).value;
		int n6left = ((java_cup.runtime.Symbol)CUP$PkmParser$stack.elementAt(CUP$PkmParser$top-10)).left;
		int n6right = ((java_cup.runtime.Symbol)CUP$PkmParser$stack.elementAt(CUP$PkmParser$top-10)).right;
		TipoBorde n6 = (TipoBorde)((java_cup.runtime.Symbol) CUP$PkmParser$stack.elementAt(CUP$PkmParser$top-10)).value;
		int n10left = ((java_cup.runtime.Symbol)CUP$PkmParser$stack.elementAt(CUP$PkmParser$top-6)).left;
		int n10right = ((java_cup.runtime.Symbol)CUP$PkmParser$stack.elementAt(CUP$PkmParser$top-6)).right;
		ClaseColor n10 = (ClaseColor)((java_cup.runtime.Symbol) CUP$PkmParser$stack.elementAt(CUP$PkmParser$top-6)).value;
		 RESULT = new Border(n4, n6, n10); 
              CUP$PkmParser$result = parser.getSymbolFactory().newSymbol("border",42, ((java_cup.runtime.Symbol)CUP$PkmParser$stack.elementAt(CUP$PkmParser$top-14)), ((java_cup.runtime.Symbol)CUP$PkmParser$stack.peek()), RESULT);
            }
          return CUP$PkmParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 63: // border ::= DIAGON STYLE CERRA 
            {
              Border RESULT =null;

              CUP$PkmParser$result = parser.getSymbolFactory().newSymbol("border",42, ((java_cup.runtime.Symbol)CUP$PkmParser$stack.elementAt(CUP$PkmParser$top-2)), ((java_cup.runtime.Symbol)CUP$PkmParser$stack.peek()), RESULT);
            }
          return CUP$PkmParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 64: // color ::= TCOLOR 
            {
              ClaseColor RESULT =null;
		int n1left = ((java_cup.runtime.Symbol)CUP$PkmParser$stack.peek()).left;
		int n1right = ((java_cup.runtime.Symbol)CUP$PkmParser$stack.peek()).right;
		TColor n1 = (TColor)((java_cup.runtime.Symbol) CUP$PkmParser$stack.peek()).value;
		 RESULT = conversor.tipoColor(n1); 
              CUP$PkmParser$result = parser.getSymbolFactory().newSymbol("color",33, ((java_cup.runtime.Symbol)CUP$PkmParser$stack.peek()), ((java_cup.runtime.Symbol)CUP$PkmParser$stack.peek()), RESULT);
            }
          return CUP$PkmParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 65: // color ::= APERT NUMERO COMA NUMERO COMA NUMERO CERRA 
            {
              ClaseColor RESULT =null;
		int n2left = ((java_cup.runtime.Symbol)CUP$PkmParser$stack.elementAt(CUP$PkmParser$top-5)).left;
		int n2right = ((java_cup.runtime.Symbol)CUP$PkmParser$stack.elementAt(CUP$PkmParser$top-5)).right;
		Double n2 = (Double)((java_cup.runtime.Symbol) CUP$PkmParser$stack.elementAt(CUP$PkmParser$top-5)).value;
		int n4left = ((java_cup.runtime.Symbol)CUP$PkmParser$stack.elementAt(CUP$PkmParser$top-3)).left;
		int n4right = ((java_cup.runtime.Symbol)CUP$PkmParser$stack.elementAt(CUP$PkmParser$top-3)).right;
		Double n4 = (Double)((java_cup.runtime.Symbol) CUP$PkmParser$stack.elementAt(CUP$PkmParser$top-3)).value;
		int n6left = ((java_cup.runtime.Symbol)CUP$PkmParser$stack.elementAt(CUP$PkmParser$top-1)).left;
		int n6right = ((java_cup.runtime.Symbol)CUP$PkmParser$stack.elementAt(CUP$PkmParser$top-1)).right;
		Double n6 = (Double)((java_cup.runtime.Symbol) CUP$PkmParser$stack.elementAt(CUP$PkmParser$top-1)).value;
		 RESULT = conversor.hslColor(n2, n4, n6); 
              CUP$PkmParser$result = parser.getSymbolFactory().newSymbol("color",33, ((java_cup.runtime.Symbol)CUP$PkmParser$stack.elementAt(CUP$PkmParser$top-6)), ((java_cup.runtime.Symbol)CUP$PkmParser$stack.peek()), RESULT);
            }
          return CUP$PkmParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 66: // color ::= PARENAPER NUMERO COMA NUMERO COMA NUMERO PARENCERRA 
            {
              ClaseColor RESULT =null;
		int n2left = ((java_cup.runtime.Symbol)CUP$PkmParser$stack.elementAt(CUP$PkmParser$top-5)).left;
		int n2right = ((java_cup.runtime.Symbol)CUP$PkmParser$stack.elementAt(CUP$PkmParser$top-5)).right;
		Double n2 = (Double)((java_cup.runtime.Symbol) CUP$PkmParser$stack.elementAt(CUP$PkmParser$top-5)).value;
		int n4left = ((java_cup.runtime.Symbol)CUP$PkmParser$stack.elementAt(CUP$PkmParser$top-3)).left;
		int n4right = ((java_cup.runtime.Symbol)CUP$PkmParser$stack.elementAt(CUP$PkmParser$top-3)).right;
		Double n4 = (Double)((java_cup.runtime.Symbol) CUP$PkmParser$stack.elementAt(CUP$PkmParser$top-3)).value;
		int n6left = ((java_cup.runtime.Symbol)CUP$PkmParser$stack.elementAt(CUP$PkmParser$top-1)).left;
		int n6right = ((java_cup.runtime.Symbol)CUP$PkmParser$stack.elementAt(CUP$PkmParser$top-1)).right;
		Double n6 = (Double)((java_cup.runtime.Symbol) CUP$PkmParser$stack.elementAt(CUP$PkmParser$top-1)).value;
		 RESULT = conversor.rgbColor(n2, n4, n6); 
              CUP$PkmParser$result = parser.getSymbolFactory().newSymbol("color",33, ((java_cup.runtime.Symbol)CUP$PkmParser$stack.elementAt(CUP$PkmParser$top-6)), ((java_cup.runtime.Symbol)CUP$PkmParser$stack.peek()), RESULT);
            }
          return CUP$PkmParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 67: // color ::= HEXADECIMAL 
            {
              ClaseColor RESULT =null;
		int n1left = ((java_cup.runtime.Symbol)CUP$PkmParser$stack.peek()).left;
		int n1right = ((java_cup.runtime.Symbol)CUP$PkmParser$stack.peek()).right;
		String n1 = (String)((java_cup.runtime.Symbol) CUP$PkmParser$stack.peek()).value;
		 RESULT = conversor.hexColor(n1); 
              CUP$PkmParser$result = parser.getSymbolFactory().newSymbol("color",33, ((java_cup.runtime.Symbol)CUP$PkmParser$stack.peek()), ((java_cup.runtime.Symbol)CUP$PkmParser$stack.peek()), RESULT);
            }
          return CUP$PkmParser$result;

          /* . . . . . .*/
          default:
            throw new Exception(
               "Invalid action number "+CUP$PkmParser$act_num+"found in internal parse table");

        }
    } /* end of method */

  /** Method splitting the generated action code into several parts. */
  public final java_cup.runtime.Symbol CUP$PkmParser$do_action(
    int                        CUP$PkmParser$act_num,
    java_cup.runtime.lr_parser CUP$PkmParser$parser,
    java.util.Stack            CUP$PkmParser$stack,
    int                        CUP$PkmParser$top)
    throws java.lang.Exception
    {
              return CUP$PkmParser$do_action_part00000000(
                               CUP$PkmParser$act_num,
                               CUP$PkmParser$parser,
                               CUP$PkmParser$stack,
                               CUP$PkmParser$top);
    }
}

}
