
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package com.example.pkm_forms_proyecto1.pkm.analizadores;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int LLAVEAPER = 16;
  public static final int CADENA = 32;
  public static final int SELECT = 24;
  public static final int IGUAL = 14;
  public static final int COLOR = 7;
  public static final int CONTENT = 8;
  public static final int APERT = 2;
  public static final int TLETRA = 31;
  public static final int LLAVECERRA = 17;
  public static final int STYLE = 26;
  public static final int SECTION = 23;
  public static final int ORIENTACION = 30;
  public static final int PARENCERRA = 21;
  public static final int TABLE = 27;
  public static final int TCOLOR = 28;
  public static final int MULTIPLE = 18;
  public static final int CERRA = 5;
  public static final int COMA = 6;
  public static final int EOF = 0;
  public static final int DROP = 10;
  public static final int TBORDE = 29;
  public static final int ELEMENT = 11;
  public static final int NUMERO = 34;
  public static final int PARENAPER = 20;
  public static final int error = 1;
  public static final int BORDER = 4;
  public static final int LINE = 15;
  public static final int TEXT = 22;
  public static final int OPEN = 19;
  public static final int HEXADECIMAL = 33;
  public static final int FAMILY = 12;
  public static final int FONT = 13;
  public static final int SIZE = 25;
  public static final int DIAGON = 9;
  public static final int BACKGROUND = 3;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "APERT",
  "BACKGROUND",
  "BORDER",
  "CERRA",
  "COMA",
  "COLOR",
  "CONTENT",
  "DIAGON",
  "DROP",
  "ELEMENT",
  "FAMILY",
  "FONT",
  "IGUAL",
  "LINE",
  "LLAVEAPER",
  "LLAVECERRA",
  "MULTIPLE",
  "OPEN",
  "PARENAPER",
  "PARENCERRA",
  "TEXT",
  "SECTION",
  "SELECT",
  "SIZE",
  "STYLE",
  "TABLE",
  "TCOLOR",
  "TBORDE",
  "ORIENTACION",
  "TLETRA",
  "CADENA",
  "HEXADECIMAL",
  "NUMERO"
  };
}

